/**
 * allocationTypeEmoji — one explicit emoji per Type bucket (plan §4 row S4b, D11).
 *
 * The allocation engine groups holdings by their raw `asset_type` value, so any
 * `AssetType` value can reach the history chart's Type dimension, plus two synthetic
 * buckets: `Liquidity` (cash) and `Unknown` (an asset without a type). Nothing throws when
 * a value is missing from the table. The chart just draws the wrong glyph, or none. The
 * table this module replaced had ten keys and fell back to the ETF emoji, which drew
 * COMMODITY, REAL_ESTATE and Unknown as ETFs. This file is what catches that failure.
 *
 * WHERE THE TYPES COME FROM. `backend/app/db/models.py`, `class AssetType(StrEnum)`, by
 * regex. They are not taken from `$lib/utils/assetTypes` (`ASSET_TYPES`, `isEtfSubtype`):
 * those import `$lib/api/generated`, which is gitignored and regenerated by `api sync`, so a
 * test reading them stays green for whoever adds an enum value and forgets the sync.
 *
 * NO COUNTS. The enum is expected to grow. Every assertion is a loop over the scrape, and
 * each loop has an anti-vacuous guard in front of it: the scrape is non-empty and contains
 * values that are certainly present.
 *
 * Pure static analysis plus a pure function: no DOM, no store, no server. The environment
 * is `node` (see vitest.config.ts), so `fs` and `path` are native here.
 */
import {existsSync, readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {describe, expect, it} from 'vitest';

import {ASSET_TYPE_EMOJI, getAssetTypeEmoji} from './allocationTypeEmoji';

// -----------------------------------------------------------------------------
// COPIED from src/lib/utils/__tests__/assetTypeTables.test.ts (the path
// constants `HERE`, `FRONTEND_DIR`, `REPO_DIR` and `MODELS_PY`, and the helpers
// `read`, `assertScraped` and `readAssetTypes`), not imported: that file is K's
// enum gate, and importing a test file registers its tests twice.
// Only the relative depth of FRONTEND_DIR is this file's own.
// -----------------------------------------------------------------------------

const HERE = path.dirname(fileURLToPath(import.meta.url));
/** `dashboard` → `components` → `lib` → `src` → `frontend` */
const FRONTEND_DIR = path.resolve(HERE, '..', '..', '..', '..');
const REPO_DIR = path.resolve(FRONTEND_DIR, '..');

const MODELS_PY = path.join(REPO_DIR, 'backend', 'app', 'db', 'models.py');

function read(file: string): string {
    expect(existsSync(file), `${file} does not exist: this gate reads it as text, so a move or a rename must stop the suite rather than silently scrape nothing`).toBe(true);
    return readFileSync(file, 'utf-8');
}

/**
 * The anti-vacuous guard. Everything below loops over a scraped collection, so
 * an empty or mis-parsed scrape has to fail *here*, naming the source, instead
 * of turning the real assertions into no-ops that pass.
 */
function assertScraped(what: string, values: string[], anchors: string[]): void {
    expect(values.length, `${what}: the scrape returned nothing. The regex no longer matches the source — every assertion built on this list would pass without checking anything.`).toBeGreaterThan(0);
    const missingAnchors = anchors.filter((anchor) => !values.includes(anchor));
    expect(missingAnchors, `${what}: the scrape is missing values that are certainly present (${anchors.join(', ')}), so it parsed the file only partially and its result cannot be trusted.`).toEqual([]);
}

/**
 * The asset types, read from the Python enum. See the header for why this is not
 * taken from the generated Zod schemas.
 */
function readAssetTypes(): string[] {
    const source = read(MODELS_PY);
    const start = source.indexOf('class AssetType(StrEnum):');
    expect(start, 'backend/app/db/models.py no longer declares "class AssetType(StrEnum)": this gate cannot find the enum it is built on.').toBeGreaterThan(-1);
    const rest = source.slice(start);
    const nextClass = rest.search(/\nclass\s+\w+/);
    const body = nextClass === -1 ? rest : rest.slice(0, nextClass);
    return [...body.matchAll(/^ {4}[A-Z][A-Z0-9_]*\s*=\s*["']([A-Z0-9_]+)["']/gm)].map((match) => match[1]);
}

// ----------------------------- end of the copy -------------------------------

const ENUM_SOURCE = 'AssetType (backend/app/db/models.py)';
/** Certainly present: anchors, not a count. ETF_MONETARY is the subtype D11 ruled on. */
const ENUM_ANCHORS = ['STOCK', 'ETF', 'OTHER', 'ETF_MONETARY'];
/** Buckets the engine adds on top of the enum: cash, and an asset without a type. */
const SYNTHETIC_BUCKETS = ['LIQUIDITY', 'UNKNOWN'];
const TABLE_SOURCE = 'src/lib/components/dashboard/allocationTypeEmoji.ts';

/** The scraped enum, guarded. Every loop starts from here, never from a bare scrape. */
function assetTypes(): string[] {
    const types = readAssetTypes();
    assertScraped(ENUM_SOURCE, types, ENUM_ANCHORS);
    return types;
}

/** The table states the entry itself, non-empty: not a fallback, not a prototype. */
function hasExplicitEntry(key: string): boolean {
    return Object.hasOwn(ASSET_TYPE_EMOJI, key) && typeof ASSET_TYPE_EMOJI[key] === 'string' && ASSET_TYPE_EMOJI[key].trim() !== '';
}

/**
 * The family of a subtype: the LONGEST proper `_`-prefix of `name` that is itself an enum
 * value, or null when there is none. `ETF_REAL_ESTATE` → `ETF` (`ETF_REAL` is not a value);
 * `REAL_ESTATE` → null (`REAL` is not a value).
 */
function familyOf(name: string, values: ReadonlySet<string>): string | null {
    const parts = name.split('_');
    for (let cut = parts.length - 1; cut > 0; cut--) {
        const prefix = parts.slice(0, cut).join('_');
        if (values.has(prefix)) return prefix;
    }
    return null;
}

/** subtype → family, for every scraped value the subtype rule applies to. */
function subtypeFamilies(types: readonly string[]): Map<string, string> {
    const values = new Set(types);
    const families = new Map<string, string>();
    for (const name of types) {
        const family = familyOf(name, values);
        if (family !== null) families.set(name, family);
    }
    return families;
}

const shown = (value: unknown): string => JSON.stringify(value) ?? String(value);

describe('allocationTypeEmoji — one explicit emoji per Type bucket (S4b, D11)', () => {
    it('reads the asset types from the Python enum', () => {
        // WHY: every case below loops over this scrape. A moved models.py or a regex that
        // stops matching must fail here, naming the source, instead of turning the loops
        // into green no-ops. The anchors are values, not a count: the enum grows.
        assertScraped(ENUM_SOURCE, readAssetTypes(), ENUM_ANCHORS);
    });

    it('has an explicit, non-empty entry for every enum value and for both synthetic buckets', () => {
        // WHY: the chart draws whatever the lookup returns and never throws. An enum value
        // added without an entry is drawn with no emoji. An emoji that comes from a fallback
        // is how COMMODITY, REAL_ESTATE and Unknown were drawn as ETFs. All gaps at once.
        const gaps = [...assetTypes(), ...SYNTHETIC_BUCKETS].filter((key) => !hasExplicitEntry(key));
        expect(gaps, `ASSET_TYPE_EMOJI has no explicit own entry for these Type buckets: ${TABLE_SOURCE}`).toEqual([]);
    });

    it('does not draw COMMODITY or REAL_ESTATE with the ETF emoji', () => {
        // WHY: both used to borrow the ETF emoji through the old fallback (D11 gives them
        // their own). Barrier: the three entries exist. Otherwise "differs from ETF" would
        // pass against a missing ETF entry.
        const missing = ['ETF', 'COMMODITY', 'REAL_ESTATE'].filter((key) => !hasExplicitEntry(key));
        expect(missing, `barrier: these entries are missing, so the comparison below would prove nothing: ${TABLE_SOURCE}`).toEqual([]);
        expect(ASSET_TYPE_EMOJI.COMMODITY, 'COMMODITY is drawn with the ETF emoji').not.toBe(ASSET_TYPE_EMOJI.ETF);
        expect(ASSET_TYPE_EMOJI.REAL_ESTATE, 'REAL_ESTATE is drawn with the ETF emoji').not.toBe(ASSET_TYPE_EMOJI.ETF);
    });

    describe('the subtype rule: a value <FAMILY>_<X>, where <FAMILY> is an enum value, carries the family emoji', () => {
        it('gives every subtype the emoji of its family', () => {
            // WHY: the emoji says what the instrument is and the label says what it holds
            // (D11). The rule is derived from the enum, so a subtype added later is covered
            // on the day it lands. At integration, `CROWDFUND_REAL_ESTATE` must get
            // CROWDFUND's emoji, not REAL_ESTATE's, and this stays red until the table has it.
            const families = subtypeFamilies(assetTypes());
            // Anti-vacuous: the derivation finds subtypes that are certainly present, with the right family.
            expect(families.get('ETF_STOCK'), `${ENUM_SOURCE}: ETF_STOCK is not derived as a subtype of ETF`).toBe('ETF');
            expect(families.get('ETF_MONETARY'), `${ENUM_SOURCE}: ETF_MONETARY is not derived as a subtype of ETF`).toBe('ETF');
            expect(families.get('ETF_REAL_ESTATE'), 'the family is the LONGEST prefix that is an enum value: ETF_REAL is not one, so ETF_REAL_ESTATE belongs to ETF').toBe('ETF');

            const familyGaps = [...new Set(families.values())].filter((family) => !hasExplicitEntry(family));
            expect(familyGaps, `barrier: these families have no entry of their own, so "same emoji as the family" would compare against nothing: ${TABLE_SOURCE}`).toEqual([]);

            const offenders = [...families].filter(([name, family]) => getAssetTypeEmoji(name) !== getAssetTypeEmoji(family)).map(([name, family]) => `${name} = ${shown(getAssetTypeEmoji(name))}, but its family ${family} = ${shown(getAssetTypeEmoji(family))}`);
            expect(offenders, `these subtypes do not carry their family's emoji: ${TABLE_SOURCE}`).toEqual([]);
        });

        it('gives every ETF_* value the ETF emoji, ETF_MONETARY included (D11)', () => {
            // WHY: D11 settled that ETF_MONETARY follows ETF rather than taking a glyph of its
            // own, as every ETF subtype shares the ETF icon in assetTypes.ts.
            const etfValues = assetTypes().filter((name) => name.startsWith('ETF_'));
            const missingAnchors = ['ETF_STOCK', 'ETF_MONETARY'].filter((anchor) => !etfValues.includes(anchor));
            expect(missingAnchors, `${ENUM_SOURCE}: the ETF_* scrape is missing values that are certainly present`).toEqual([]);
            expect(hasExplicitEntry('ETF'), `barrier: ETF has no entry of its own: ${TABLE_SOURCE}`).toBe(true);

            const offenders = etfValues.filter((name) => getAssetTypeEmoji(name) !== ASSET_TYPE_EMOJI.ETF).map((name) => `${name} = ${shown(getAssetTypeEmoji(name))}`);
            expect(offenders, `these ETF subtypes are not drawn with the ETF emoji ${shown(ASSET_TYPE_EMOJI.ETF)}: ${TABLE_SOURCE}`).toEqual([]);
        });

        it('leaves REAL_ESTATE out of the rule: REAL is not an enum value', () => {
            // WHY: REAL_ESTATE has a subtype's shape but is a type of its own. Its emoji is
            // its own entry, never the ETF one. If a REAL value ever joins the enum, this case
            // turns red and the choice becomes explicit.
            const types = assetTypes();
            expect(types, `barrier: ${ENUM_SOURCE} no longer lists REAL_ESTATE, so "not a subtype" would prove nothing`).toContain('REAL_ESTATE');
            expect(subtypeFamilies(types).has('REAL_ESTATE'), 'REAL_ESTATE is derived as a subtype').toBe(false);
            expect(hasExplicitEntry('REAL_ESTATE'), `REAL_ESTATE has no entry of its own: ${TABLE_SOURCE}`).toBe(true);
            expect(getAssetTypeEmoji('REAL_ESTATE'), 'REAL_ESTATE is drawn with the ETF emoji').not.toBe(ASSET_TYPE_EMOJI.ETF);
        });
    });

    it('looks names up case-insensitively, and Unknown is ❓', () => {
        // WHY: the synthetic buckets arrive as `Liquidity` and `Unknown`, not in upper case.
        // A lookup that stops upper-casing draws cash and untyped assets with no emoji.
        // Barrier: each upper-case key resolves to an emoji, or '' === '' would pass.
        const pairs = [
            ['Liquidity', 'LIQUIDITY'],
            ['unknown', 'UNKNOWN'],
            ['etf_bond', 'ETF_BOND'],
        ] as const;
        for (const [raw, key] of pairs) {
            expect(getAssetTypeEmoji(key), `barrier: ${key} resolves to no emoji`).not.toBe('');
            expect(getAssetTypeEmoji(raw), `${raw} does not resolve like ${key}`).toBe(getAssetTypeEmoji(key));
        }
        // D11 (developer, 2026-09-24): Unknown is ❓ in the Type dimension, as in Sector.
        expect(getAssetTypeEmoji('unknown')).toBe('❓');
    });

    it("returns '' for an unmapped value, never another type's emoji", () => {
        // WHY: the old fallback lent the ETF emoji to anything unmapped. `constructor` is an
        // Object.prototype name, so a lookup that stops upper-casing returns the inherited
        // function instead of ''. Barrier: a mapped value resolves, so the '' below is the
        // fallback and not a broken lookup.
        expect(getAssetTypeEmoji('STOCK'), 'barrier: STOCK resolves to no emoji').not.toBe('');
        for (const raw of ['NOT_A_TYPE', '', 'constructor']) {
            expect(getAssetTypeEmoji(raw), `${shown(raw)} is not a Type bucket, yet it resolves to something`).toBe('');
        }
    });
});
