"""
Scalable Capital overnight account import plugin for BRIM.

The overnight account (*conto deposito*, Tagesgeld) has no export in Scalable's app: the
LibreFolio exporter (``Librefolio/librefolio-exporter``) writes it as its own file, with
the 14 columns of Scalable's broker CSV and ``lf_*`` columns (account, account index,
transaction id, exact type, reversal).

It goes into its own broker in LibreFolio, next to the broker account's
(``broker_scalable``): the transfers between the two show up on both sides and are merged
into cash transfers in the bulk editor. Each plugin refuses the other account's file and
names the plugin that reads it. The shared reader, with the mapping rules, is
``_scalable.py``.
"""

from pathlib import Path
from typing import List, Optional

from backend.app.schemas.brim import BRIMParseOutput, BRIMRefusal
from backend.app.services.brim_provider import BRIMProvider
from backend.app.services.brim_providers import _scalable
from backend.app.services.provider_registry import BRIMProviderRegistry, register_provider


@register_provider(BRIMProviderRegistry)
class ScalableDepositProvider(BRIMProvider):
    """Scalable Capital overnight account: the LibreFolio exporter's overnight account file."""

    @property
    def provider_code(self) -> str:
        return "broker_scalable_deposit"

    @property
    def provider_name(self) -> str:
        return "Scalable Capital overnight account"

    @property
    def description(self) -> str:
        return "Import the Scalable Capital overnight account (Tagesgeld) from the LibreFolio exporter's file: interest with the tax withheld, deposits, withdrawals and transfers to the broker account."

    @property
    def supported_extensions(self) -> List[str]:
        return [".csv"]

    @property
    def detection_priority(self) -> int:
        """High priority - specific broker plugin."""
        return 100

    @property
    def icon_url(self) -> str:
        """Scalable's logo with the liquidity asset-type badge, generated by ``scripts/compose_broker_icons.py``."""
        return self.generate_static_url("scalable/deposit.png")

    @property
    def plugin_version(self) -> str:
        return "1.0.0"

    @property
    def docs_url(self) -> Optional[str]:
        return "/mkdocs/user/transactions/import/scalable/"

    @property
    def test_file_pattern(self) -> Optional[str]:
        """Filename pattern for auto-detection tests."""
        return "scalable-deposit"

    @property
    def history_tag(self) -> str:
        """Both Scalable plugins tag their transactions ``scalable``: the two sides of a merged transfer keep the same tags."""
        return "scalable"

    def can_parse(self, file_path: Path) -> bool:
        """The exporter's overnight account file: decided by the header and the ``lf_account`` values."""
        return _scalable.accepts(self, file_path, _scalable.DEPOSIT)

    def cannot_parse_detail(self, file_path: Path) -> Optional[BRIMRefusal]:
        """The broker account's file (exporter or Scalable's own), or a file mixing both accounts: say which plugin reads it."""
        return _scalable.refusal(self, file_path, _scalable.DEPOSIT)

    def cannot_parse_reason(self, file_path: Path) -> Optional[str]:
        detail = self.cannot_parse_detail(file_path)
        return detail.message if detail else None

    def parse(self, file_path: Path, broker_id: int) -> BRIMParseOutput:
        return _scalable.parse(self, file_path, broker_id, _scalable.DEPOSIT)
