"""
Scalable Capital broker account import plugin for BRIM.

Reads the two exports of the broker account, told apart by their header:

- **Scalable's own CSV** (PRIME and PRIME+ plans only): 14 columns, ``;``, decimal comma;
- **the LibreFolio exporter's broker file** (``Librefolio/librefolio-exporter``, any plan):
  the same 14 columns, then ``lf_*`` columns with the transaction id, the exact type and
  the parts of the fee.

The overnight account (*conto deposito*, Tagesgeld) has its own plugin,
``broker_scalable_deposit``, and its own broker in LibreFolio: each plugin refuses the
other account's file and names the plugin that reads it. The shared reader, with the
mapping rules, is ``_scalable.py``.
"""

from pathlib import Path
from typing import List, Optional

from backend.app.schemas.brim import BRIMParseOutput, BRIMRefusal
from backend.app.services.brim_provider import BRIMProvider
from backend.app.services.brim_providers import _scalable
from backend.app.services.provider_registry import BRIMProviderRegistry, register_provider


@register_provider(BRIMProviderRegistry)
class ScalableBrokerProvider(BRIMProvider):
    """Scalable Capital broker account: Scalable's own CSV (PRIME) or the LibreFolio exporter's broker file."""

    @property
    def provider_code(self) -> str:
        return "broker_scalable"

    @property
    def provider_name(self) -> str:
        return "Scalable Capital broker"

    @property
    def description(self) -> str:
        return "Import the Scalable Capital broker account from Scalable's own CSV export (PRIME) or from the LibreFolio exporter's broker file: trades with their fees and taxes, savings plans, dividends, interest, deposits, withdrawals and transfers to the overnight account."

    @property
    def supported_extensions(self) -> List[str]:
        return [".csv"]

    @property
    def detection_priority(self) -> int:
        """High priority - specific broker plugin."""
        return 100

    @property
    def icon_url(self) -> str:
        """Scalable's logo with the stock asset-type badge, generated by ``scripts/compose_broker_icons.py``."""
        return self.generate_static_url("scalable/broker.png")

    @property
    def plugin_version(self) -> str:
        return "1.0.0"

    @property
    def docs_url(self) -> Optional[str]:
        return "/mkdocs/user/transactions/import/scalable/"

    @property
    def test_file_pattern(self) -> Optional[str]:
        """Filename pattern for auto-detection tests: never ``scalable`` alone, which also names the overnight account's sample."""
        return "scalable-broker"

    @property
    def test_file_patterns(self) -> List[str]:
        return ["scalable-prime", "scalable-broker"]

    def can_parse(self, file_path: Path) -> bool:
        """Scalable's own CSV, or the exporter's broker file: decided by the header and the ``lf_account`` values."""
        return _scalable.accepts(self, file_path, _scalable.BROKER)

    def cannot_parse_detail(self, file_path: Path) -> Optional[BRIMRefusal]:
        """The overnight account's file, or a file mixing both accounts: say which plugin reads it."""
        return _scalable.refusal(self, file_path, _scalable.BROKER)

    def cannot_parse_reason(self, file_path: Path) -> Optional[str]:
        detail = self.cannot_parse_detail(file_path)
        return detail.message if detail else None

    def parse(self, file_path: Path, broker_id: int) -> BRIMParseOutput:
        return _scalable.parse(self, file_path, broker_id, _scalable.BROKER)
