/**
 * asset type ↔ UI tables — the frontend half of the enum gate.
 *
 * `AssetType` is the backend's enum, and several hand-written tables in this
 * frontend are keyed on it. Every one of them has a fallback, and every one of
 * those fallbacks is silent:
 *
 *   - `PNG_MAP` misses an entry            → the type is drawn as `other.png`
 *   - the PNG it names is not on disk      → a broken `<img>`, hidden by `onerror`
 *   - an i18n file misses a label          → the raw key `assets.types.X` is rendered
 *   - `BADGE_CLASS_MAP` misses an entry    → the badge falls back to grey
 *   - a type filter list misses a value    → the type becomes un-filterable
 *   - `ASSET_TYPE_FAMILY` misfiles a type  → the type select lists it in the wrong
 *                                            group, or in none at all
 *   - a composite icon was never generated → the subtype loses its picture, as above
 *
 * None of these throw. Adding a value to the enum and forgetting a table
 * produces no failure anywhere — just a wrong picture, an untranslated string,
 * or a row nobody can filter to. This file is the only thing that will say so.
 *
 * ## Families, composites and the tree (workstream K: R15–R17)
 *
 * The taxonomy has two levels. `ASSET_TYPE_FAMILY` files each subtype under its
 * container (`ETF_STOCK` is an `ETF`), `ASSET_TYPE_CONTENT_ICON` names what it
 * contains, and the icon of a subtype is the composite of the two, generated by
 * `scripts/compose_asset_type_icons.py` from those very tables read as text. The
 * blocks at the end of this file hold the three tables to each other and to the
 * enum, and call `buildAssetTypeTree()` — the select of the asset dialog — to
 * check that what it builds out of them is what they say.
 *
 * ## Where the list of types comes from
 *
 * From `backend/app/db/models.py`, by regex, deliberately — **not** from
 * `$lib/api/generated`. That file is gitignored and regenerated by
 * `./dev.py api sync`; a test reading it would pass for a developer who added an
 * enum value and forgot to re-sync, which is exactly the desynchronisation this
 * test exists to catch. Reading the Python source makes this a real
 * backend↔frontend contract rather than a check of the frontend against itself.
 *
 * ## Why every parse is asserted before it is used
 *
 * Every assertion here is a loop over a scraped list. A regex that matches
 * nothing turns all of them into no-ops and the file reports green while
 * checking nothing — worse than the bug it guards. So each scrape is proved
 * non-empty and anchored on values known to be present before anything is
 * concluded from it.
 *
 * There is no count assertion anywhere on purpose: the enum is expected to
 * grow, and a `toHaveLength(9)` would make this gate an obstacle instead.
 *
 * Pure static analysis: no DOM, no store, no server, no database. `environment`
 * is `node` (see vitest.config.ts), so `fs` and `path` are native here.
 */
import {existsSync, readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {describe, expect, it} from 'vitest';

const HERE = path.dirname(fileURLToPath(import.meta.url));
/** `__tests__` → `utils` → `lib` → `src` → `frontend` */
const FRONTEND_DIR = path.resolve(HERE, '..', '..', '..', '..');
const REPO_DIR = path.resolve(FRONTEND_DIR, '..');

const MODELS_PY = path.join(REPO_DIR, 'backend', 'app', 'db', 'models.py');
const ASSET_TYPES_TS = path.join(FRONTEND_DIR, 'src', 'lib', 'utils', 'assetTypes.ts');
const GENERATED_TS = path.join(FRONTEND_DIR, 'src', 'lib', 'api', 'generated.ts');
const ASSET_TABLE_SVELTE = path.join(FRONTEND_DIR, 'src', 'lib', 'components', 'assets', 'AssetTable.svelte');
const ASSET_CARD_SVELTE = path.join(FRONTEND_DIR, 'src', 'lib', 'components', 'assets', 'AssetCard.svelte');
const ASSETS_PAGE_SVELTE = path.join(FRONTEND_DIR, 'src', 'routes', '(app)', 'assets', '+page.svelte');
const ASSET_TYPE_SELECT_SVELTE = path.join(FRONTEND_DIR, 'src', 'lib', 'components', 'ui', 'select', 'AssetTypeSelect.svelte');
const ICON_DIR = path.join(FRONTEND_DIR, 'static', 'icons', 'asset-types');
/** The documentation ships its own copy of the icons; the composer writes both. */
const DOCS_ICON_DIR = path.join(REPO_DIR, 'mkdocs_src', 'docs', 'static', 'icons', 'asset-types');
const I18N_LANGUAGES = ['en', 'it', 'fr', 'es'] as const;

function read(file: string): string {
    expect(existsSync(file), `${file} does not exist: this gate reads it as text, so a move or a rename must stop the suite rather than silently scrape nothing`).toBe(true);
    return readFileSync(file, 'utf-8');
}

/**
 * The anti-vacuous guard. Everything below loops over a scraped collection, so
 * an empty or mis-parsed scrape has to fail *here*, naming the source, instead
 * of turning the real assertions into no-ops that pass.
 */
function assertScraped(what: string, values: string[], anchors: string[]): void {
    expect(values.length, `${what}: the scrape returned nothing. The regex no longer matches the source — every assertion built on this list would pass without checking anything.`).toBeGreaterThan(0);
    const missingAnchors = anchors.filter((anchor) => !values.includes(anchor));
    expect(missingAnchors, `${what}: the scrape is missing values that are certainly present (${anchors.join(', ')}), so it parsed the file only partially and its result cannot be trusted.`).toEqual([]);
}

/** Extract a single `const NAME: Record<string, string> = { ... };` object literal. */
function scrapeRecordKeys(source: string, declaration: RegExp, what: string): string[] {
    const declarations = [...source.matchAll(new RegExp(declaration.source, 'g'))];
    expect(declarations.length, `${what}: expected exactly one declaration to scrape, found ${declarations.length}. An ambiguous or absent match means this gate is reading the wrong block.`).toBe(1);
    const start = declarations[0].index! + declarations[0][0].length;
    const end = source.indexOf('};', start);
    expect(end, `${what}: the object literal is never closed with "};" — the scrape has no boundary.`).toBeGreaterThan(start);
    return [...source.slice(start, end).matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*:/gm)].map((match) => match[1]);
}

/**
 * The asset types, read from the Python enum. See the header for why this is not
 * taken from the generated Zod schemas.
 */
function readAssetTypes(): string[] {
    const source = read(MODELS_PY);
    const start = source.indexOf('class AssetType(StrEnum):');
    expect(start, 'backend/app/db/models.py no longer declares "class AssetType(StrEnum)": this gate cannot find the enum it is built on.').toBeGreaterThan(-1);
    const rest = source.slice(start);
    const nextClass = rest.search(/\nclass\s+\w+/);
    const body = nextClass === -1 ? rest : rest.slice(0, nextClass);
    return [...body.matchAll(/^ {4}[A-Z][A-Z0-9_]*\s*=\s*["']([A-Z0-9_]+)["']/gm)].map((match) => match[1]);
}

const ASSET_TYPES = readAssetTypes();

/** Report every gap at once: a red that names one type per run is a red read four times. */
function expectNoGaps(missing: string[], explanation: string): void {
    expect(missing, explanation).toEqual([]);
}

/**
 * The `KEY: 'value'` entries of one `const NAME: … = { … };` literal in assetTypes.ts.
 *
 * The declaration is matched the way `scripts/compose_asset_type_icons.py` matches it —
 * `export` optional, any type annotation — so the gate and the generator of the composite
 * icons read the same tables with the same eyes. Every key must carry a plain single-quoted
 * value: a key whose value the regex cannot read would otherwise drop out of every check
 * built on the table, silently, instead of failing one of them.
 */
function readRecord(name: string, anchors: string[]): Map<string, string> {
    const what = `${name} (src/lib/utils/assetTypes.ts)`;
    const source = read(ASSET_TYPES_TS);
    const declarations = [...source.matchAll(new RegExp(`(?:export\\s+)?const\\s+${name}\\s*:[^=]*=\\s*\\{`, 'g'))];
    expect(declarations.length, `${what}: expected exactly one declaration to scrape, found ${declarations.length}. An ambiguous or absent match means this gate is reading the wrong block.`).toBe(1);
    const start = declarations[0].index! + declarations[0][0].length;
    const end = source.indexOf('};', start);
    expect(end, `${what}: the object literal is never closed with "};" — the scrape has no boundary.`).toBeGreaterThan(start);
    const body = source.slice(start, end);
    const keys = [...body.matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*:/gm)].map((match) => match[1]);
    assertScraped(what, keys, anchors);
    const entries = [...body.matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*:\s*'([^']*)'/gm)].map((match) => [match[1], match[2]] as const);
    expect(
        entries.map(([key]) => key),
        `${what}: some entries are not plain single-quoted strings, so their values cannot be read as text and would drop out of every check built on this table.`,
    ).toEqual(keys);
    expect(new Set(keys).size, `${what}: a key is declared twice. JavaScript keeps the last one without a word, so the table does not do what it reads as.`).toBe(keys.length);
    return new Map(entries);
}

/**
 * The screen order of the type select, read as text. It is never imported, for the reason
 * given in the creation-menu test below: on a checkout without `generated.ts` an import
 * would compare an empty list to an empty list and report success.
 */
function readMenuOrder(): string[] {
    const source = read(ASSET_TYPES_TS);
    const declarations = [...source.matchAll(/export const ASSET_TYPE_MENU_ORDER\s*:\s*readonly string\[\]\s*=\s*\[/g)];
    expect(declarations.length, `assetTypes.ts: expected exactly one ASSET_TYPE_MENU_ORDER declaration to scrape, found ${declarations.length}.`).toBe(1);
    const start = declarations[0].index! + declarations[0][0].length;
    const end = source.indexOf('];', start);
    expect(end, 'assetTypes.ts: the ASSET_TYPE_MENU_ORDER array is never closed with "];".').toBeGreaterThan(start);
    const menu = [...source.slice(start, end).matchAll(/'([A-Z][A-Z0-9_]*)'/g)].map((match) => match[1]);
    assertScraped('ASSET_TYPE_MENU_ORDER (src/lib/utils/assetTypes.ts)', menu, ['STOCK', 'ETF', 'OTHER']);
    return menu;
}

/**
 * First and last entry of the ETF block, and the crowdfunding one: a scrape that holds all
 * three crossed the whole literal rather than stopping at a line it could not parse.
 */
const FAMILY_ANCHORS = ['ETF_STOCK', 'ETF_MONETARY', 'CROWDFUND_REAL_ESTATE'];

/** `ASSET_TYPE_FAMILY` (subtype → container) and the containers it names, both guarded. */
function readFamilies(): {family: Map<string, string>; containers: string[]} {
    const family = readRecord('ASSET_TYPE_FAMILY', FAMILY_ANCHORS);
    const containers = [...new Set(family.values())];
    assertScraped('family containers (the values of ASSET_TYPE_FAMILY)', containers, ['ETF', 'CROWDFUND']);
    return {family, containers};
}

/** The part of an i18n catalogue the type select reads beyond `assets.types`. */
interface AssetsCatalogue {
    typeSections?: Record<string, unknown>;
    typeHints?: Record<string, unknown>;
    typeSelect?: Record<string, unknown>;
}

function readAssetsCatalogue(language: string): AssetsCatalogue {
    const catalogue = JSON.parse(read(path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`))) as {assets?: AssetsCatalogue};
    return catalogue.assets ?? {};
}

function nonEmpty(value: unknown): boolean {
    return typeof value === 'string' && value.trim() !== '';
}

describe('asset type tables', () => {
    it('reads the asset types from the Python enum', () => {
        // Guards the source of every loop below. `OTHER` is an anchor, not an
        // expectation about the size of the enum — no count is asserted here.
        assertScraped('AssetType (backend/app/db/models.py)', ASSET_TYPES, ['STOCK', 'ETF', 'OTHER']);
        expect(new Set(ASSET_TYPES).size, 'the enum scrape returned duplicates, so the regex is matching something that is not an enum member').toBe(ASSET_TYPES.length);
    });

    it('maps every asset type to an icon in PNG_MAP', () => {
        // `PNG_MAP` is module-private, so it is scraped rather than imported —
        // importing assetTypes.ts would also pull in the gitignored generated client.
        const mapped = scrapeRecordKeys(read(ASSET_TYPES_TS), /const PNG_MAP\s*:\s*Record<string,\s*string>\s*=\s*\{/, 'PNG_MAP (src/lib/utils/assetTypes.ts)');
        assertScraped('PNG_MAP (src/lib/utils/assetTypes.ts)', mapped, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !mapped.includes(type)),
            'PNG_MAP has no entry for these asset types. getAssetTypeIconUrl() falls back to "other" without warning, so they are drawn with the wrong icon everywhere: src/lib/utils/assetTypes.ts',
        );
    });

    it('names a PNG that exists on disk for every asset type', () => {
        const source = read(ASSET_TYPES_TS);
        const start = source.indexOf('const PNG_MAP');
        const end = source.indexOf('};', start);
        const entries = [...source.slice(start, end).matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*:\s*'([^']+)'/gm)].map((match) => [match[1], match[2]] as const);
        assertScraped(
            'PNG_MAP filenames (src/lib/utils/assetTypes.ts)',
            entries.map(([type]) => type),
            ['STOCK', 'ETF', 'OTHER'],
        );
        const filenames = new Map(entries);

        expectNoGaps(
            ASSET_TYPES.filter((type) => filenames.has(type) && !existsSync(path.join(ICON_DIR, `${filenames.get(type)}.png`))).map((type) => `${type} -> ${filenames.get(type)}.png`),
            'PNG_MAP points at icon files that are not in frontend/static/icons/asset-types/. The <img> carries onerror="this.style.display=\'none\'", so the badge simply loses its icon and nothing is logged.',
        );
    });

    it.each(I18N_LANGUAGES)('has an %s label for every asset type', (language) => {
        const file = path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`);
        const labels = JSON.parse(read(file))?.assets?.types ?? {};
        // Structured input, but the path can still move: guard it like the rest.
        assertScraped(`assets.types (src/lib/i18n/${language}.json)`, Object.keys(labels), ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => typeof labels[type] !== 'string' || labels[type].trim() === ''),
            `src/lib/i18n/${language}.json has no assets.types entry for these asset types. The i18n layer renders the raw key, so the user sees "assets.types.X" in the badge and in every asset-type dropdown.`,
        );
        // No assertion on the label text itself: the point is that a label
        // exists in each language, not what any of them says.
    });

    it('gives every asset type a badge colour', () => {
        const colours = scrapeRecordKeys(read(ASSET_TYPES_TS), /const BADGE_CLASS_MAP\s*:\s*Record<string,\s*string>\s*=\s*\{/, 'BADGE_CLASS_MAP (src/lib/utils/assetTypes.ts)');
        assertScraped('BADGE_CLASS_MAP (src/lib/utils/assetTypes.ts)', colours, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !colours.includes(type)),
            'assetTypeBadgeClass() in src/lib/utils/assetTypes.ts has no colour for these asset types. The lookup ends in BADGE_CLASS_FALLBACK, so they all render as the same anonymous grey badge — in the table and on the cards alike — and become indistinguishable.',
        );
    });

    it('renders the badge from that one map in both views', () => {
        // AssetTable and AssetCard each used to carry their own hand-written colour
        // map, and the two had already drifted: the card had no INDEX, no explicit
        // OTHER, and a switch statement instead of a lookup. Checking the shared map
        // above is only worth something while both views actually read it.
        for (const [label, file] of [
            ['AssetTable.svelte', ASSET_TABLE_SVELTE],
            ['AssetCard.svelte', ASSET_CARD_SVELTE],
        ] as const) {
            expect(read(file).includes('assetTypeBadgeClass'), `${label} no longer calls assetTypeBadgeClass(). If it has gone back to its own colour map, that map is unguarded and will drift from the enum exactly as it did before.`).toBe(true);
        }
    });

    it('offers every asset type in the AssetTable type filter', () => {
        const source = read(ASSET_TABLE_SVELTE);
        const declarations = [...source.matchAll(/enumOptions:\s*\[/g)];
        expect(declarations.length, `AssetTable.svelte: expected exactly one enumOptions list to scrape, found ${declarations.length}.`).toBe(1);
        const start = declarations[0].index! + declarations[0][0].length;
        const end = source.indexOf(']', start);
        expect(end, 'AssetTable.svelte: the enumOptions array is never closed.').toBeGreaterThan(start);
        const offered = [...source.slice(start, end).matchAll(/'([A-Z][A-Z0-9_]*)'/g)].map((match) => match[1]);
        assertScraped('enumOptions (AssetTable.svelte)', offered, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !offered.includes(type)),
            "the enumOptions list of the type column in src/lib/components/assets/AssetTable.svelte does not include these asset types. That list is the column's set of selectable type values: a type missing from it can never be chosen, and the omission is reported nowhere. (The column currently also carries filterable: false, which suppresses the symptom without fixing the list.)",
        );
    });

    it('offers every asset type in the type filter of the assets page, and nothing else', () => {
        const source = read(ASSETS_PAGE_SVELTE);
        const declarations = [...source.matchAll(/const\s+ALL_ASSET_TYPES\b[^=]*=\s*\[/g)];
        expect(declarations.length, `routes/(app)/assets/+page.svelte: expected exactly one ALL_ASSET_TYPES declaration to scrape, found ${declarations.length}.`).toBe(1);
        const start = declarations[0].index! + declarations[0][0].length;
        const end = source.indexOf(']', start);
        expect(end, 'routes/(app)/assets/+page.svelte: the ALL_ASSET_TYPES array is never closed.').toBeGreaterThan(start);
        const offered = [...source.slice(start, end).matchAll(/'([A-Z][A-Z0-9_]*)'/g)].map((match) => match[1]);
        assertScraped('ALL_ASSET_TYPES (routes/(app)/assets/+page.svelte)', offered, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !offered.includes(type)),
            'ALL_ASSET_TYPES in src/routes/(app)/assets/+page.svelte does not list these asset types. It is the only source of the type filter of the assets page, so a type missing from it is never offered there — and worse: the list keeps an asset only while its type is in the active filter set, and "select all" selects only the listed types, so the moment any type filter is on, every asset of a missing type silently vanishes from the page.',
        );
        // Bidirectional, but the second direction is a different kind of wrong. The page
        // offers only the types it counts among the loaded assets, and the backend never
        // returns a type its enum does not define, so an extra value here can never reach
        // the screen: it is dead weight — typically the stale half of a rename whose new
        // half the assertion above is reporting at the same time.
        expectNoGaps(
            offered.filter((type) => !ASSET_TYPES.includes(type)),
            'ALL_ASSET_TYPES in src/routes/(app)/assets/+page.svelte lists values the backend AssetType enum does not define. No asset can ever carry them, so the filter never shows them: a stale entry, most likely the old name of a renamed type.',
        );
        expect(new Set(offered).size, 'ALL_ASSET_TYPES lists the same asset type more than once: the type filter of the assets page would show a duplicate row.').toBe(offered.length);
    });

    it('offers every asset type in the creation menu, and nothing else', () => {
        const menu = readMenuOrder();

        expectNoGaps(
            ASSET_TYPES.filter((type) => !menu.includes(type)),
            'ASSET_TYPE_MENU_ORDER in src/lib/utils/assetTypes.ts does not list these asset types. It is the only source of the asset type select in the creation and edit dialog, so a type missing here cannot be chosen by any user, anywhere, and nothing reports it. This list used to be mapped straight from the enum and so was complete for free; it is hand-written now only to keep each family together, and this assertion is the price of that.',
        );
        // Bidirectional on purpose, unlike the lookup tables above. An extra value in a
        // lookup table is dead weight; an extra value *here* is offered to the user and
        // then rejected by the backend, because the enum is what the API validates.
        expectNoGaps(
            menu.filter((type) => !ASSET_TYPES.includes(type)),
            'ASSET_TYPE_MENU_ORDER in src/lib/utils/assetTypes.ts offers these values, but the backend AssetType enum does not define them. The dialog would let the user pick one and the API would reject the save.',
        );
        expect(new Set(menu).size, 'ASSET_TYPE_MENU_ORDER lists the same asset type more than once: the select would show a duplicate row.').toBe(menu.length);

        // The ETF family read by its *name*, on purpose: this check therefore also holds an
        // ETF_* value that nobody filed in ASSET_TYPE_FAMILY. The check for every family,
        // container first, reads that table instead (families block, below).
        const familyPositions = menu.map((type, index) => ({type, index})).filter(({type}) => type === 'ETF' || type.startsWith('ETF_'));
        expect(familyPositions.length, 'ASSET_TYPE_MENU_ORDER no longer contains the ETF family at all.').toBeGreaterThan(1);
        const span = familyPositions[familyPositions.length - 1].index - familyPositions[0].index + 1;
        expect(
            span,
            `the ETF family is not contiguous in ASSET_TYPE_MENU_ORDER (it spans ${span} slots for ${familyPositions.length} members). buildAssetTypeTree() gathers every member into the ETF group wherever it is listed, so a split family no longer appears in the order this array states — and the array is documented as the single place that decides it.`,
        ).toBe(familyPositions.length);
    });

    it.each(I18N_LANGUAGES)('has an %s title for the ETF section', (language) => {
        const file = path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`);
        const sections = JSON.parse(read(file))?.assets?.typeSections ?? {};
        expect(typeof sections.ETF === 'string' && sections.ETF.trim() !== '', `src/lib/i18n/${language}.json has no assets.typeSections.ETF. The dropdown prints the raw key as the section title, so the user reads "assets.typeSections.ETF" above the ETF rows.`).toBe(true);
    });

    /**
     * The engine's synthetic cash bucket, upper-cased.
     *
     * `portfolio_engine.py` injects the cash slice into `by_type` and `by_sector`
     * under the literal `"Liquidity"` — Title Case, and not a member of
     * `AssetType`. It then travels the same type-keyed path as the real enum
     * values, so it needs a label under `assets.types` that no enum value will
     * ever name. The three assertions below hold that arrangement together.
     */
    const CASH_BUCKET_KEY = 'LIQUIDITY';

    it('keeps the cash bucket out of the asset type enum', () => {
        expect(
            ASSET_TYPES.includes(CASH_BUCKET_KEY),
            `${CASH_BUCKET_KEY} has become an AssetType. Cash is an account balance the engine injects, not an instrument anyone buys, and a money-market fund already has its own value (ETF_MONETARY). An enum member with this name would be counted twice: once as a real holding and once as the synthetic slice.`,
        ).toBe(false);
    });

    it('keeps primaryAssetType upper-casing its input', () => {
        const source = read(ASSET_TYPES_TS);
        const start = source.indexOf('export function primaryAssetType');
        expect(start, 'src/lib/utils/assetTypes.ts no longer exports primaryAssetType: contract K2 has moved or gone.').toBeGreaterThan(-1);
        const body = source.slice(start, source.indexOf('\n}', start));

        expect(
            body.includes('.toUpperCase()'),
            'primaryAssetType no longer upper-cases its input. AllocationHistoryChart resolves its label by concatenating "assets.types." with rawName.toUpperCase(), so the engine\'s Title Case "Liquidity" lines up with the catalogue only while both sides normalise the same way. Returning unknown input verbatim looks tidier and silently makes the cash slice miss every table keyed on the upper-case form — the colour first, since the label would still resolve.',
        ).toBe(true);
    });

    it.each(I18N_LANGUAGES)('has an %s label for the cash bucket, which no enum value names', (language) => {
        const file = path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`);
        const labels = JSON.parse(read(file))?.assets?.types ?? {};
        assertScraped(`assets.types (src/lib/i18n/${language}.json)`, Object.keys(labels), ['STOCK', 'ETF', 'OTHER']);

        expect(
            typeof labels[CASH_BUCKET_KEY] === 'string' && labels[CASH_BUCKET_KEY].trim() !== '',
            `src/lib/i18n/${language}.json has no assets.types.${CASH_BUCKET_KEY}. That key is the one entry under assets.types with no matching AssetType, and nothing references it literally because AllocationHistoryChart composes it — \`assets.types.\${rawName.toUpperCase()}\` — so no search, no linter and no static pass will ever connect the two. It looks dead, and it looks dead for a convincing reason. Deleting it makes the cash slice of the allocation chart print the raw key instead of a translation, in every language at once.`,
        ).toBe(true);
    });
});

/**
 * Contract K2 — `primaryAssetType`, as its consumers rely on it.
 *
 * The cash-bucket block above already pins the *text* of the function: it reads the
 * source and checks that `.toUpperCase()` is still in the body. That is a weaker net
 * than it looks. Changing the last line from `?? raw` to `?? type` leaves the
 * `.toUpperCase()` call untouched on the line above and hands the caller its own
 * spelling straight back — the textual assertion stays green while the contract is
 * gone. These two call the function instead.
 *
 * The property matters outside this file. G indexes a chart palette on the result, E
 * and F read the same contract, and every one of those tables answers an unknown key
 * with a fallback rather than an error: a grey badge, `other.png`, the raw i18n path.
 * Nobody verifies the invariant they all depend on, which is why it is pinned here,
 * once, where the function lives — and not a second time in each consumer's suite.
 */
describe('contract K2 — primaryAssetType behaviour', () => {
    /**
     * `assetTypes.ts` imports `$lib/api/generated`, which is gitignored. Every other
     * test in this file scrapes rather than imports precisely so that it still works
     * on a checkout where `api sync` has never run; a static import here would drag
     * all of them into that dependency, because one unresolvable import fails the
     * whole module at collection. So the import is dynamic and local to the two tests
     * that must genuinely *call* the function — behaviour cannot be scraped.
     *
     * A missing `generated.ts` is reported, not skipped: in a summary line a skipped
     * assertion about K2 and a satisfied one are the same absence of red.
     */
    async function importPrimaryAssetType(): Promise<(type: string | null | undefined) => string> {
        expect(existsSync(GENERATED_TS), 'src/lib/api/generated.ts is absent, so assetTypes.ts cannot be imported and this contract cannot be exercised. Run `./dev.py api sync`.').toBe(true);
        const module = await import('../assetTypes');
        expect(typeof module.primaryAssetType, 'src/lib/utils/assetTypes.ts no longer exports primaryAssetType: contract K2 has moved or gone.').toBe('function');
        return module.primaryAssetType;
    }

    it('returns an upper-case value for every spelling a caller can hand it', async () => {
        const primaryAssetType = await importPrimaryAssetType();
        const inputs = [
            ...ASSET_TYPES,
            ...ASSET_TYPES.map((type) => type.toLowerCase()),
            '  etf_stock  ',
            'Etf_Monetary',
            // The engine's own spelling of the synthetic cash bucket, injected Title Case
            // by portfolio_engine.py into by_type and by_sector alike.
            'Liquidity',
            'SOMETHING_NOBODY_HAS_ADDED_YET',
        ];
        assertScraped('primaryAssetType inputs', inputs, ['STOCK', 'ETF', 'OTHER']);

        const offenders = inputs.filter((input) => primaryAssetType(input) !== primaryAssetType(input).toUpperCase());
        expect(
            offenders,
            'primaryAssetType returned a value that is not upper-case for these inputs. Every table keyed on its result — the chart palette, PNG_MAP, BADGE_CLASS_MAP, the assets.types catalogue — looks the key up verbatim and answers a miss with a fallback instead of an error, so a single mixed-case result is not a crash but a wrong colour, a wrong icon and a raw i18n path, in four languages, with nothing logged.',
        ).toEqual([]);
    });

    it('folds nullish and blank input to OTHER, never to the empty string', async () => {
        const primaryAssetType = await importPrimaryAssetType();
        for (const input of [null, undefined, '', '   ']) {
            expect(
                primaryAssetType(input),
                `primaryAssetType(${JSON.stringify(input)}) must be "OTHER". Returning "" would be worse than returning a wrong type: no catalogue, palette or icon map holds an empty key, so every one of them would fall back at once and the slice would be drawn grey, unlabelled and untraceable. The whitespace case is the reason the implementation trims before it tests.`,
            ).toBe('OTHER');
        }
    });
});

/**
 * R15 — the families of the asset type select (T4).
 *
 * `ASSET_TYPE_FAMILY` is the *container* view of the taxonomy — `ETF_STOCK` is an ETF — and the
 * deliberate counterpart of `primaryAssetType()`, the *content* view — `ETF_STOCK` holds STOCK.
 * The select builds one group per family out of the first, the badge colour follows the second,
 * and the composite icons are generated from both. None of the three fails loudly when a table
 * is wrong: a subtype simply lands in the wrong group, or in none, or wears the wrong colour.
 */
describe('asset type families (R15)', () => {
    it('files every subtype under an enum value, and never a family inside a family', () => {
        const {family, containers} = readFamilies();

        expectNoGaps(
            [...family.keys()].filter((subtype) => !ASSET_TYPES.includes(subtype)),
            'ASSET_TYPE_FAMILY in src/lib/utils/assetTypes.ts files these values as subtypes, but the backend AssetType enum does not define them: dead entries, or a rename that stopped halfway.',
        );
        expectNoGaps(
            [...family].filter(([, container]) => !ASSET_TYPES.includes(container)).map(([subtype, container]) => `${subtype} -> ${container}`),
            'ASSET_TYPE_FAMILY names containers that are not AssetType values. buildAssetTypeTree() opens a family group only when its walk over ASSET_TYPE_MENU_ORDER — enum values only — reaches the container, and it skips every subtype where it is listed, so the members of these families appear nowhere in the asset dialog.',
        );
        expectNoGaps(
            [...family].filter(([, container]) => family.has(container)).map(([subtype, container]) => `${subtype} -> ${container}`),
            'ASSET_TYPE_FAMILY nests a family inside a family: these containers are subtypes themselves. buildAssetTypeTree() skips a subtype wherever it is listed and waits for its container, so a container that is also a subtype never opens a group of its own, and its members vanish from the select with it. The select has two levels, and so must this table.',
        );
        // A naming tripwire, not a derivation (primaryAssetType's doc says why the string is
        // never split to *compute* a type): a value spelled like a member of an existing
        // family and yet not filed in it is, in all likelihood, a forgotten entry.
        expectNoGaps(
            ASSET_TYPES.filter((type) => containers.some((container) => type.startsWith(`${container}_`) && family.get(type) !== container)),
            'these AssetType values are named like members of an existing family, but ASSET_TYPE_FAMILY does not file them there. The select would list them at the root, away from their family, and scripts/compose_asset_type_icons.py would never draw their composite. File them in ASSET_TYPE_FAMILY and ASSET_TYPE_CONTENT_ICON — or, if one genuinely belongs to no family, make this tripwire say so.',
        );
    });

    it('gives a content pastille to every subtype, and to subtypes only', () => {
        const {family} = readFamilies();
        const content = readRecord('ASSET_TYPE_CONTENT_ICON', FAMILY_ANCHORS);

        expectNoGaps(
            [...family.keys()].filter((subtype) => !content.has(subtype)),
            'ASSET_TYPE_CONTENT_ICON has no pastille for these subtypes. scripts/compose_asset_type_icons.py refuses to run while the two tables disagree, so no composite icon can be generated for them.',
        );
        expectNoGaps(
            [...content.keys()].filter((type) => !family.has(type)),
            'ASSET_TYPE_CONTENT_ICON gives a pastille to types that ASSET_TYPE_FAMILY does not file as subtypes: a dead entry, or a subtype whose family entry was forgotten — in which case it is also missing from its group in the select.',
        );
    });

    it('keeps every family contiguous in the menu, its container first', () => {
        const menu = readMenuOrder();
        const {family, containers} = readFamilies();
        const problems: string[] = [];

        for (const container of containers) {
            const members = [container, ...[...family].filter(([, owner]) => owner === container).map(([subtype]) => subtype)];
            const unlisted = members.filter((member) => !menu.includes(member));
            if (unlisted.length > 0) {
                // Reported by the creation-menu test as well; here it only keeps the slots below meaningful.
                problems.push(`${container}: ${unlisted.join(', ')} not in the menu at all`);
                continue;
            }
            const slots = members.map((member) => menu.indexOf(member));
            const first = Math.min(...slots);
            const last = Math.max(...slots);
            if (menu[first] !== container) problems.push(`${container}: ${menu[first]} is listed before its container`);
            const intruders = menu.slice(first, last + 1).filter((type) => !members.includes(type));
            if (intruders.length > 0) problems.push(`${container}: ${intruders.join(', ')} wedged inside the family`);
        }

        expectNoGaps(
            problems,
            "ASSET_TYPE_MENU_ORDER in src/lib/utils/assetTypes.ts does not keep these families together with their container first. buildAssetTypeTree() gathers a family into its container's group wherever the members are listed and always heads it with the container, so the select stops showing the order this array states — and the array is documented as the single place that decides it.",
        );
    });

    it.each(I18N_LANGUAGES)('has an %s group title and a generic-member hint for every family', (language) => {
        const {containers} = readFamilies();
        const assets = readAssetsCatalogue(language);

        expectNoGaps(
            containers.filter((container) => !nonEmpty(assets.typeSections?.[container])).map((container) => `assets.typeSections.${container}`),
            `src/lib/i18n/${language}.json has no group title for these families. buildAssetTypeTree() heads each family group with it, and svelte-i18n answers a missing key with the key itself, so the user reads the raw path above the group.`,
        );
        expectNoGaps(
            containers.filter((container) => !nonEmpty(assets.typeHints?.[container])).map((container) => `assets.typeHints.${container}`),
            `src/lib/i18n/${language}.json has no hint for the generic member of these families. The hint is the line that tells the plain container — mixed or unstated content — apart from its subtypes; without it the row shows the raw key under its label.`,
        );
    });

    const TYPE_SELECT_TEXTS = ['searchPlaceholder', 'noMatches'] as const;

    it.each(I18N_LANGUAGES)('has an %s search placeholder and empty-state text for the type select', (language) => {
        const typeSelect = readAssetsCatalogue(language).typeSelect;

        expectNoGaps(
            TYPE_SELECT_TEXTS.filter((key) => !nonEmpty(typeSelect?.[key])).map((key) => `assets.typeSelect.${key}`),
            `src/lib/i18n/${language}.json is missing these texts of the asset type select: its search box and its "no match" state would print the raw key.`,
        );
    });

    it('keeps the type select reading those two texts', () => {
        const source = read(ASSET_TYPE_SELECT_SVELTE);

        expectNoGaps(
            TYPE_SELECT_TEXTS.filter((key) => !source.includes(`'assets.typeSelect.${key}'`)),
            'src/lib/components/ui/select/AssetTypeSelect.svelte no longer reads these keys. The catalogue check above is worth something only while the component displays what it checks: renamed on one side only, it keeps passing over keys nobody shows.',
        );
    });

    it('colours every badge by what the asset contains: badge(x) is badge(primary(x))', () => {
        const badge = readRecord('BADGE_CLASS_MAP', ['STOCK', 'ETF', 'OTHER']);
        // Scraped, like everything in this block: primaryAssetType() is this map plus "itself".
        const primary = readRecord('PRIMARY_TYPE_MAP', ['ETF_STOCK', 'CROWDFUND_REAL_ESTATE']);
        const primaryOf = (type: string) => primary.get(type) ?? type;

        expectNoGaps(
            ASSET_TYPES.filter((type) => badge.get(type) !== badge.get(primaryOf(type))).map((type) => `${type} (contains ${primaryOf(type)})`),
            'BADGE_CLASS_MAP in src/lib/utils/assetTypes.ts colours these types differently from the base type they contain (PRIMARY_TYPE_MAP, i.e. primaryAssetType()). The badge answers "what am I exposed to?" — an equity ETF is blue like a share, real-estate crowdfunding teal like real estate — which is what makes a list scannable by exposure. A colour picked by hand here breaks that for one type, and nothing else would ever notice.',
        );
    });
});

/**
 * The subtypes whose pastille does not follow D61, each with the decision that made it one.
 *
 * D61 draws the pastille of a subtype from the base type it contains, `PNG_MAP[primary(x)]`, and
 * has nothing to say only where that base type is the subtype itself. Adding a row here is the
 * only way to add an exception: without this table, a pastille that drifted from the rule and a
 * pastille that was told to differ would look exactly the same.
 */
const PASTILLE_EXCEPTIONS: Readonly<Record<string, {icon: string; decision: string}>> = {
    ETF_MONETARY: {icon: 'liquidity', decision: 'D67: a money-market fund contains no base type — cash is a balance, not an asset anyone buys — so it borrows the icon of the cash bucket'},
};

/**
 * R16 — the composite icons of the subtypes (T6).
 *
 * A subtype is drawn with the icon of its container, whole, and a pastille in the corner saying
 * what it contains (D52). The files are generated by `scripts/compose_asset_type_icons.py` from
 * the three tables scraped here, into the app and into the documentation; `PNG_MAP` must name
 * exactly the file the generator writes, or `getAssetTypeIconUrl()` asks for one that is not there.
 */
describe('composite icons of the subtypes (R16)', () => {
    it('names every subtype icon {container}-{content} and ships it to the app and to the docs', () => {
        const png = readRecord('PNG_MAP', ['STOCK', 'ETF', 'OTHER']);
        const {family} = readFamilies();
        const content = readRecord('ASSET_TYPE_CONTENT_ICON', FAMILY_ANCHORS);
        const misnamed: string[] = [];
        for (const [subtype, container] of family) {
            const composite = `${png.get(container)}-${content.get(subtype)}`;
            if (png.get(subtype) !== composite) misnamed.push(`${subtype}: PNG_MAP names '${png.get(subtype)}', the convention requires '${composite}'`);
        }

        expectNoGaps(
            misnamed,
            'PNG_MAP in src/lib/utils/assetTypes.ts does not name these subtypes after their composite, {PNG_MAP[container]}-{ASSET_TYPE_CONTENT_ICON[subtype]}. That is the file scripts/compose_asset_type_icons.py writes (and the script refuses to run while the names disagree), so the app would request a picture nobody generates.',
        );

        const missing: string[] = [];
        for (const directory of [ICON_DIR, DOCS_ICON_DIR]) {
            expect(existsSync(directory), `${path.relative(REPO_DIR, directory)} does not exist: the composite icons are generated into it, so a move must stop this gate rather than report every file as missing.`).toBe(true);
            for (const subtype of family.keys()) {
                const file = path.join(directory, `${png.get(subtype)}.png`);
                if (!existsSync(file)) missing.push(`${subtype} -> ${path.relative(REPO_DIR, file)}`);
            }
        }
        expectNoGaps(
            missing,
            'these composite icons are not on disk. In the app the <img> hides itself on error, so the subtype silently loses its picture; in the documentation the page shows a broken image. Regenerate them with scripts/compose_asset_type_icons.py (its --check mode compares the files on disk with a fresh build) and commit both copies.',
        );
    });

    it('fills every pastille with the icon of the base type the subtype contains (D61), save the declared exceptions (D67)', () => {
        const png = readRecord('PNG_MAP', ['STOCK', 'ETF', 'OTHER']);
        const {family} = readFamilies();
        const content = readRecord('ASSET_TYPE_CONTENT_ICON', FAMILY_ANCHORS);
        const primary = readRecord('PRIMARY_TYPE_MAP', ['ETF_STOCK', 'CROWDFUND_REAL_ESTATE']);
        const primaryOf = (type: string) => primary.get(type) ?? type;

        // An exception is admissible only where the rule is silent: a subtype that rolls up to itself.
        expectNoGaps(
            Object.keys(PASTILLE_EXCEPTIONS).filter((type) => !family.has(type) || primaryOf(type) !== type),
            'PASTILLE_EXCEPTIONS in this file declares exceptions that D61 does not need: these types are not subtypes, or they now roll up to a base type whose icon the rule can use. Drop the exception rather than keep a second rule for them.',
        );

        const offenders: string[] = [];
        for (const subtype of family.keys()) {
            const exception = PASTILLE_EXCEPTIONS[subtype];
            const expected = exception?.icon ?? png.get(primaryOf(subtype));
            if (content.get(subtype) === expected) continue;
            if (!exception && primaryOf(subtype) === subtype) offenders.push(`${subtype}: rolls up to itself, so D61 has no base type to draw — declare its pastille in PASTILLE_EXCEPTIONS, with the decision that chose it`);
            else offenders.push(`${subtype}: pastille '${content.get(subtype)}', expected '${expected}' (${exception ? exception.decision : `PNG_MAP[${primaryOf(subtype)}]`})`);
        }
        expectNoGaps(
            offenders,
            'ASSET_TYPE_CONTENT_ICON in src/lib/utils/assetTypes.ts draws these subtypes with a pastille that is not the icon of what they contain. The pastille says what the instrument holds — the same thing its badge colour says — so a pastille that disagrees with primaryAssetType() tells the user one thing in the corner and another in the badge.',
        );

        const unborrowable = Object.entries(PASTILLE_EXCEPTIONS)
            .filter(([, {icon}]) => !existsSync(path.join(ICON_DIR, `${icon}.png`)))
            .map(([type, {icon}]) => `${type} -> ${icon}.png`);
        expectNoGaps(unborrowable, 'the icons these exceptions borrow are not in frontend/static/icons/asset-types/: scripts/compose_asset_type_icons.py draws the pastille from that file and stops without it.');
    });
});

/**
 * R15 — the tree of the asset type select, and the family view, called for real (T5).
 *
 * The blocks above prove the tables agree; these prove that `buildAssetTypeTree()` makes of them
 * what they say. They need `assetTypes.ts` imported, hence `generated.ts`: the import is dynamic
 * and local, exactly as in the K2 block and for the same reason, and a missing client is reported
 * rather than skipped.
 *
 * The translator is the identity. Every label is then its own i18n key, which lets these tests
 * say *which* key a row reads — the keys the catalogue checks above guard — without asserting a
 * single translated word.
 */
describe('the asset type tree and the family view (R15)', () => {
    async function importAssetTypes(): Promise<typeof import('../assetTypes')> {
        expect(existsSync(GENERATED_TS), 'src/lib/api/generated.ts is absent, so assetTypes.ts cannot be imported and the type select cannot be built. Run `./dev.py api sync`.').toBe(true);
        const module = await import('../assetTypes');
        for (const name of ['buildAssetTypeTree', 'assetTypeFamily', 'isEtfSubtype', 'getAssetTypeIconUrl'] as const) {
            expect(typeof module[name], `src/lib/utils/assetTypes.ts no longer exports ${name}().`).toBe('function');
        }
        return module;
    }

    const identity = (key: string) => key;

    /** Imported by other workstreams, workstream I among them, which read them and never change them. */
    const STABLE_EXPORTS = ['ASSET_TYPES', 'ETF_SUBTYPES', 'isEtfSubtype', 'primaryAssetType', 'getAssetTypeIconUrl', 'assetTypeBadgeClass'];

    it('still exports what the rest of the app imports from it', () => {
        const source = read(ASSET_TYPES_TS);

        expectNoGaps(
            STABLE_EXPORTS.filter((name) => !new RegExp(`^export\\s+(?:const|function)\\s+${name}\\b`, 'm').test(source)),
            'src/lib/utils/assetTypes.ts no longer exports these names. The R14–R16 rewrite of this module promised to leave them alone, because code outside this workstream imports them: renamed or dropped here, they break a consumer this workstream does not build.',
        );
    });

    it('lists every asset type exactly once, in the order of ASSET_TYPE_MENU_ORDER', async () => {
        const {buildAssetTypeTree, ASSET_TYPE_MENU_ORDER} = await importAssetTypes();
        const values = buildAssetTypeTree(identity).flatMap((group) => group.items.map((item) => item.value));
        assertScraped('the rows of buildAssetTypeTree()', values, ['STOCK', 'ETF', 'OTHER']);
        const occurrences = (type: string) => values.filter((value) => value === type).length;

        expectNoGaps(
            ASSET_TYPES.filter((type) => occurrences(type) !== 1).map((type) => `${type} ×${occurrences(type)}`),
            'buildAssetTypeTree() does not list these asset types exactly once. ×0 is a type nobody can choose in the asset dialog; ×2 is a duplicate row, and the copy a search lands on may be the wrong one.',
        );
        expectNoGaps(
            values.filter((value) => !ASSET_TYPES.includes(value)),
            'buildAssetTypeTree() offers rows that are not AssetType values: the dialog would let the user pick one and the API would reject the save.',
        );
        expect(values, 'the rows of buildAssetTypeTree() do not follow ASSET_TYPE_MENU_ORDER, the single place documented to decide the screen order of the type select.').toEqual([...ASSET_TYPE_MENU_ORDER]);
    });

    it('makes one collapsible group per family and keeps every other type inline, at the root', async () => {
        const {buildAssetTypeTree, ASSET_TYPE_FAMILY, getAssetTypeIconUrl} = await importAssetTypes();
        const groups = buildAssetTypeTree(identity);
        const containers = [...new Set(Object.values(ASSET_TYPE_FAMILY))];
        assertScraped('family containers (ASSET_TYPE_FAMILY)', containers, ['ETF', 'CROWDFUND']);
        const problems: string[] = [];

        for (const container of containers) {
            const matching = groups.filter((group) => group.key === container);
            if (matching.length !== 1) {
                problems.push(`${container}: ${matching.length} groups keyed on it`);
                continue;
            }
            const [group] = matching;
            if (group.inline) problems.push(`${container}: inline, so the family cannot be opened or closed`);
            if (group.label !== `assets.typeSections.${container}`) problems.push(`${container}: titled ${JSON.stringify(group.label)} instead of assets.typeSections.${container}`);
            if (group.icon !== getAssetTypeIconUrl(container)) problems.push(`${container}: group icon ${JSON.stringify(group.icon)} instead of ${getAssetTypeIconUrl(container)}`);
        }
        for (const group of groups) {
            if (!containers.includes(group.key) && group.inline !== true) problems.push(`${group.key}: a collapsible group that is not a family`);
        }
        groups.forEach((group, index) => {
            // A root run ends only where a family begins: two in a row would draw a separator between neighbours of the same level.
            if (group.inline && groups[index + 1]?.inline) problems.push(`${group.key}, ${groups[index + 1].key}: two root runs in a row`);
        });

        expectNoGaps(problems, 'buildAssetTypeTree() does not shape the select as R15 describes it: the types that specialise nothing sit at the root, in inline groups, and each family is one group, headed by its own title and icon, that opens and closes.');
    });

    it('heads each family with its generic member, the only row that carries a hint', async () => {
        const {buildAssetTypeTree, ASSET_TYPE_FAMILY} = await importAssetTypes();
        const groups = buildAssetTypeTree(identity);
        assertScraped(
            'the family groups of buildAssetTypeTree()',
            groups.filter((group) => !group.inline).map((group) => group.key),
            ['ETF', 'CROWDFUND'],
        );
        const problems: string[] = [];

        for (const group of groups) {
            if (group.inline) {
                for (const item of group.items) {
                    if (item.family !== undefined) problems.push(`${item.value}: at the root, yet marked as a member of ${item.family}`);
                    if (item.hint !== undefined) problems.push(`${item.value}: at the root, yet carries a hint`);
                }
                continue;
            }
            const [head, ...members] = group.items;
            if (head?.value !== group.key) problems.push(`${group.key}: headed by ${head?.value ?? 'nothing'} instead of its generic member`);
            if (head?.hint !== `assets.typeHints.${group.key}`) problems.push(`${group.key}: its generic member's hint is ${JSON.stringify(head?.hint)} instead of assets.typeHints.${group.key}`);
            for (const member of members) {
                if (member.hint !== undefined) problems.push(`${member.value}: a subtype carrying a hint`);
            }
            for (const item of group.items) {
                if (item.family !== group.key) problems.push(`${item.value}: listed in ${group.key}, marked as a member of ${item.family ?? 'nothing'}`);
            }
            const filed = Object.keys(ASSET_TYPE_FAMILY)
                .filter((type) => ASSET_TYPE_FAMILY[type] === group.key)
                .sort();
            const listed = members.map((member) => member.value).sort();
            if (filed.join() !== listed.join()) problems.push(`${group.key}: lists ${listed.join(', ') || 'no subtype'}, ASSET_TYPE_FAMILY files ${filed.join(', ') || 'none'}`);
        }

        expectNoGaps(
            problems,
            'buildAssetTypeTree() does not build the families as decided in D-K1: a group row only opens the family, so the choice "an ETF of mixed or unstated content" is a row of its own — the generic member, first in its group and the only row with a hint saying what generic means there. Rows at the root belong to no family.',
        );
    });

    it('labels, draws and indexes every row by its own type', async () => {
        const {buildAssetTypeTree, getAssetTypeIconUrl} = await importAssetTypes();
        const items = buildAssetTypeTree(identity).flatMap((group) => group.items);
        assertScraped(
            'the rows of buildAssetTypeTree()',
            items.map((item) => item.value),
            ['STOCK', 'ETF', 'OTHER'],
        );
        const problems: string[] = [];

        for (const item of items) {
            if (item.label !== `assets.types.${item.value}`) problems.push(`${item.value}: labelled ${JSON.stringify(item.label)} instead of assets.types.${item.value}`);
            if (item.icon !== getAssetTypeIconUrl(item.value)) problems.push(`${item.value}: icon ${item.icon} instead of ${getAssetTypeIconUrl(item.value)}`);
            if (item.searchText !== item.searchText.toLowerCase()) problems.push(`${item.value}: searchText is not lower-case`);
            for (const part of [item.value, item.label, item.hint]) {
                if (part && !item.searchText.includes(part.toLowerCase())) problems.push(`${item.value}: searchText does not hold "${part}"`);
            }
        }

        expectNoGaps(
            problems,
            'buildAssetTypeTree() builds rows that do not describe their own type. TreeSelect matches searchText as given against a lower-cased query, so a row must carry its enum value (a code-minded user types etf_bond), its label and its hint, all lower-cased; the icon must be the one the rest of the app draws for the type, and the label must come from the assets.types catalogue this file checks in four languages.',
        );
    });

    it('resolves the family of any spelling a caller can hand assetTypeFamily()', async () => {
        const {assetTypeFamily} = await importAssetTypes();
        const cases: Array<[string | null | undefined, string]> = [
            ['ETF_STOCK', 'ETF'],
            ['etf_stock', 'ETF'],
            ['  Crowdfund_Real_Estate  ', 'CROWDFUND'],
            // The generic member is its own family, like every type that specialises nothing.
            ['ETF', 'ETF'],
            ['CROWDFUND', 'CROWDFUND'],
            ['STOCK', 'STOCK'],
            // Unknown input keeps its name, upper-cased — K2's rule: a value nobody mapped must stay visible, not fold into OTHER.
            ['something_nobody_added_yet', 'SOMETHING_NOBODY_ADDED_YET'],
            [null, 'OTHER'],
            [undefined, 'OTHER'],
            ['', 'OTHER'],
            ['   ', 'OTHER'],
        ];

        expectNoGaps(
            cases.filter(([input, expected]) => assetTypeFamily(input) !== expected).map(([input, expected]) => `assetTypeFamily(${JSON.stringify(input)}) is ${JSON.stringify(assetTypeFamily(input))}, expected ${expected}`),
            'assetTypeFamily() in src/lib/utils/assetTypes.ts no longer answers the contract handed to Risk: the six ETF_* resolve to ETF, CROWDFUND_REAL_ESTATE to CROWDFUND, every other type to itself; case and surrounding spaces are ignored, unknown input keeps its (upper-cased) name, and only nullish or blank input falls back to OTHER.',
        );
        expectNoGaps(
            ASSET_TYPES.filter((type) => {
                const family = assetTypeFamily(type);
                return !ASSET_TYPES.includes(family) || assetTypeFamily(family) !== family;
            }),
            'assetTypeFamily() resolves these asset types to something that is not a family of its own — not an enum value, or a value that resolves further. A caller grouping by family would build groups that no table is keyed on.',
        );
    });

    it('keeps isEtfSubtype() to the ETF family minus its generic member, so real-estate crowdfunding is no ETF', async () => {
        const {isEtfSubtype, assetTypeFamily} = await importAssetTypes();

        expect(isEtfSubtype('ETF_STOCK'), 'isEtfSubtype() no longer recognises ETF_STOCK: the negative below would pass for a function that answers false to everything.').toBe(true);
        expect(isEtfSubtype('CROWDFUND_REAL_ESTATE'), 'isEtfSubtype() calls CROWDFUND_REAL_ESTATE an ETF subtype. It is a crowdfunding loan backed by property; callers that treat ETF subtypes as exchange-traded wrappers would treat it as one.').toBe(false);
        expectNoGaps(
            ASSET_TYPES.filter((type) => isEtfSubtype(type) !== (type !== 'ETF' && assetTypeFamily(type) === 'ETF')),
            'isEtfSubtype() (the ETF_SUBTYPES list) and ASSET_TYPE_FAMILY disagree on these values. They are two spellings of the same fact — which values specialise ETF — and a value added to one list only is an ETF for half the app.',
        );
    });
});
