/**
 * asset type ↔ UI tables — the frontend half of the enum gate.
 *
 * `AssetType` is the backend's enum, and four hand-written tables in this
 * frontend are keyed on it. Every one of them has a fallback, and every one of
 * those fallbacks is silent:
 *
 *   - `PNG_MAP` misses an entry            → the type is drawn as `other.png`
 *   - the PNG it names is not on disk      → a broken `<img>`, hidden by `onerror`
 *   - an i18n file misses a label          → the raw key `assets.types.X` is rendered
 *   - `BADGE_CLASS_MAP` misses an entry    → the badge falls back to grey
 *   - the table filter list misses a value → the type becomes un-filterable
 *
 * None of these throw. Adding a value to the enum and forgetting a table
 * produces no failure anywhere — just a wrong picture, an untranslated string,
 * or a row nobody can filter to. This file is the only thing that will say so.
 *
 * ## Where the list of types comes from
 *
 * From `backend/app/db/models.py`, by regex, deliberately — **not** from
 * `$lib/api/generated`. That file is gitignored and regenerated by
 * `./dev.py api sync`; a test reading it would pass for a developer who added an
 * enum value and forgot to re-sync, which is exactly the desynchronisation this
 * test exists to catch. Reading the Python source makes this a real
 * backend↔frontend contract rather than a check of the frontend against itself.
 *
 * ## Why every parse is asserted before it is used
 *
 * Every assertion here is a loop over a scraped list. A regex that matches
 * nothing turns all of them into no-ops and the file reports green while
 * checking nothing — worse than the bug it guards. So each scrape is proved
 * non-empty and anchored on values known to be present before anything is
 * concluded from it.
 *
 * There is no count assertion anywhere on purpose: the enum is expected to
 * grow, and a `toHaveLength(9)` would make this gate an obstacle instead.
 *
 * Pure static analysis: no DOM, no store, no server, no database. `environment`
 * is `node` (see vitest.config.ts), so `fs` and `path` are native here.
 */
import {existsSync, readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {describe, expect, it} from 'vitest';

const HERE = path.dirname(fileURLToPath(import.meta.url));
/** `__tests__` → `utils` → `lib` → `src` → `frontend` */
const FRONTEND_DIR = path.resolve(HERE, '..', '..', '..', '..');
const REPO_DIR = path.resolve(FRONTEND_DIR, '..');

const MODELS_PY = path.join(REPO_DIR, 'backend', 'app', 'db', 'models.py');
const ASSET_TYPES_TS = path.join(FRONTEND_DIR, 'src', 'lib', 'utils', 'assetTypes.ts');
const GENERATED_TS = path.join(FRONTEND_DIR, 'src', 'lib', 'api', 'generated.ts');
const ASSET_TABLE_SVELTE = path.join(FRONTEND_DIR, 'src', 'lib', 'components', 'assets', 'AssetTable.svelte');
const ASSET_CARD_SVELTE = path.join(FRONTEND_DIR, 'src', 'lib', 'components', 'assets', 'AssetCard.svelte');
const ICON_DIR = path.join(FRONTEND_DIR, 'static', 'icons', 'asset-types');
const I18N_LANGUAGES = ['en', 'it', 'fr', 'es'] as const;

function read(file: string): string {
    expect(existsSync(file), `${file} does not exist: this gate reads it as text, so a move or a rename must stop the suite rather than silently scrape nothing`).toBe(true);
    return readFileSync(file, 'utf-8');
}

/**
 * The anti-vacuous guard. Everything below loops over a scraped collection, so
 * an empty or mis-parsed scrape has to fail *here*, naming the source, instead
 * of turning the real assertions into no-ops that pass.
 */
function assertScraped(what: string, values: string[], anchors: string[]): void {
    expect(values.length, `${what}: the scrape returned nothing. The regex no longer matches the source — every assertion built on this list would pass without checking anything.`).toBeGreaterThan(0);
    const missingAnchors = anchors.filter((anchor) => !values.includes(anchor));
    expect(missingAnchors, `${what}: the scrape is missing values that are certainly present (${anchors.join(', ')}), so it parsed the file only partially and its result cannot be trusted.`).toEqual([]);
}

/** Extract a single `const NAME: Record<string, string> = { ... };` object literal. */
function scrapeRecordKeys(source: string, declaration: RegExp, what: string): string[] {
    const declarations = [...source.matchAll(new RegExp(declaration.source, 'g'))];
    expect(declarations.length, `${what}: expected exactly one declaration to scrape, found ${declarations.length}. An ambiguous or absent match means this gate is reading the wrong block.`).toBe(1);
    const start = declarations[0].index! + declarations[0][0].length;
    const end = source.indexOf('};', start);
    expect(end, `${what}: the object literal is never closed with "};" — the scrape has no boundary.`).toBeGreaterThan(start);
    return [...source.slice(start, end).matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*:/gm)].map((match) => match[1]);
}

/**
 * The asset types, read from the Python enum. See the header for why this is not
 * taken from the generated Zod schemas.
 */
function readAssetTypes(): string[] {
    const source = read(MODELS_PY);
    const start = source.indexOf('class AssetType(StrEnum):');
    expect(start, 'backend/app/db/models.py no longer declares "class AssetType(StrEnum)": this gate cannot find the enum it is built on.').toBeGreaterThan(-1);
    const rest = source.slice(start);
    const nextClass = rest.search(/\nclass\s+\w+/);
    const body = nextClass === -1 ? rest : rest.slice(0, nextClass);
    return [...body.matchAll(/^ {4}[A-Z][A-Z0-9_]*\s*=\s*["']([A-Z0-9_]+)["']/gm)].map((match) => match[1]);
}

const ASSET_TYPES = readAssetTypes();

/** Report every gap at once: a red that names one type per run is a red read four times. */
function expectNoGaps(missing: string[], explanation: string): void {
    expect(missing, explanation).toEqual([]);
}

describe('asset type tables', () => {
    it('reads the asset types from the Python enum', () => {
        // Guards the source of every loop below. `OTHER` is an anchor, not an
        // expectation about the size of the enum — no count is asserted here.
        assertScraped('AssetType (backend/app/db/models.py)', ASSET_TYPES, ['STOCK', 'ETF', 'OTHER']);
        expect(new Set(ASSET_TYPES).size, 'the enum scrape returned duplicates, so the regex is matching something that is not an enum member').toBe(ASSET_TYPES.length);
    });

    it('maps every asset type to an icon in PNG_MAP', () => {
        // `PNG_MAP` is module-private, so it is scraped rather than imported —
        // importing assetTypes.ts would also pull in the gitignored generated client.
        const mapped = scrapeRecordKeys(read(ASSET_TYPES_TS), /const PNG_MAP\s*:\s*Record<string,\s*string>\s*=\s*\{/, 'PNG_MAP (src/lib/utils/assetTypes.ts)');
        assertScraped('PNG_MAP (src/lib/utils/assetTypes.ts)', mapped, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !mapped.includes(type)),
            'PNG_MAP has no entry for these asset types. getAssetTypeIconUrl() falls back to "other" without warning, so they are drawn with the wrong icon everywhere: src/lib/utils/assetTypes.ts',
        );
    });

    it('names a PNG that exists on disk for every asset type', () => {
        const source = read(ASSET_TYPES_TS);
        const start = source.indexOf('const PNG_MAP');
        const end = source.indexOf('};', start);
        const entries = [...source.slice(start, end).matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*:\s*'([^']+)'/gm)].map((match) => [match[1], match[2]] as const);
        assertScraped(
            'PNG_MAP filenames (src/lib/utils/assetTypes.ts)',
            entries.map(([type]) => type),
            ['STOCK', 'ETF', 'OTHER'],
        );
        const filenames = new Map(entries);

        expectNoGaps(
            ASSET_TYPES.filter((type) => filenames.has(type) && !existsSync(path.join(ICON_DIR, `${filenames.get(type)}.png`))).map((type) => `${type} -> ${filenames.get(type)}.png`),
            'PNG_MAP points at icon files that are not in frontend/static/icons/asset-types/. The <img> carries onerror="this.style.display=\'none\'", so the badge simply loses its icon and nothing is logged.',
        );
    });

    it.each(I18N_LANGUAGES)('has an %s label for every asset type', (language) => {
        const file = path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`);
        const labels = JSON.parse(read(file))?.assets?.types ?? {};
        // Structured input, but the path can still move: guard it like the rest.
        assertScraped(`assets.types (src/lib/i18n/${language}.json)`, Object.keys(labels), ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => typeof labels[type] !== 'string' || labels[type].trim() === ''),
            `src/lib/i18n/${language}.json has no assets.types entry for these asset types. The i18n layer renders the raw key, so the user sees "assets.types.X" in the badge and in every asset-type dropdown.`,
        );
        // No assertion on the label text itself: the point is that a label
        // exists in each language, not what any of them says.
    });

    it('gives every asset type a badge colour', () => {
        const colours = scrapeRecordKeys(read(ASSET_TYPES_TS), /const BADGE_CLASS_MAP\s*:\s*Record<string,\s*string>\s*=\s*\{/, 'BADGE_CLASS_MAP (src/lib/utils/assetTypes.ts)');
        assertScraped('BADGE_CLASS_MAP (src/lib/utils/assetTypes.ts)', colours, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !colours.includes(type)),
            'assetTypeBadgeClass() in src/lib/utils/assetTypes.ts has no colour for these asset types. The lookup ends in BADGE_CLASS_FALLBACK, so they all render as the same anonymous grey badge — in the table and on the cards alike — and become indistinguishable.',
        );
    });

    it('renders the badge from that one map in both views', () => {
        // AssetTable and AssetCard each used to carry their own hand-written colour
        // map, and the two had already drifted: the card had no INDEX, no explicit
        // OTHER, and a switch statement instead of a lookup. Checking the shared map
        // above is only worth something while both views actually read it.
        for (const [label, file] of [
            ['AssetTable.svelte', ASSET_TABLE_SVELTE],
            ['AssetCard.svelte', ASSET_CARD_SVELTE],
        ] as const) {
            expect(read(file).includes('assetTypeBadgeClass'), `${label} no longer calls assetTypeBadgeClass(). If it has gone back to its own colour map, that map is unguarded and will drift from the enum exactly as it did before.`).toBe(true);
        }
    });

    it('offers every asset type in the AssetTable type filter', () => {
        const source = read(ASSET_TABLE_SVELTE);
        const declarations = [...source.matchAll(/enumOptions:\s*\[/g)];
        expect(declarations.length, `AssetTable.svelte: expected exactly one enumOptions list to scrape, found ${declarations.length}.`).toBe(1);
        const start = declarations[0].index! + declarations[0][0].length;
        const end = source.indexOf(']', start);
        expect(end, 'AssetTable.svelte: the enumOptions array is never closed.').toBeGreaterThan(start);
        const offered = [...source.slice(start, end).matchAll(/'([A-Z][A-Z0-9_]*)'/g)].map((match) => match[1]);
        assertScraped('enumOptions (AssetTable.svelte)', offered, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !offered.includes(type)),
            "the enumOptions list of the type column in src/lib/components/assets/AssetTable.svelte does not include these asset types. That list is the column's set of selectable type values: a type missing from it can never be chosen, and the omission is reported nowhere. (The column currently also carries filterable: false, which suppresses the symptom without fixing the list.)",
        );
    });

    it('offers every asset type in the creation menu, and nothing else', () => {
        const source = read(ASSET_TYPES_TS);
        const declarations = [...source.matchAll(/export const ASSET_TYPE_MENU_ORDER\s*:\s*readonly string\[\]\s*=\s*\[/g)];
        expect(declarations.length, `assetTypes.ts: expected exactly one ASSET_TYPE_MENU_ORDER declaration to scrape, found ${declarations.length}.`).toBe(1);
        const start = declarations[0].index! + declarations[0][0].length;
        const end = source.indexOf('];', start);
        expect(end, 'assetTypes.ts: the ASSET_TYPE_MENU_ORDER array is never closed with "];".').toBeGreaterThan(start);
        const menu = [...source.slice(start, end).matchAll(/'([A-Z][A-Z0-9_]*)'/g)].map((match) => match[1]);
        assertScraped('ASSET_TYPE_MENU_ORDER (src/lib/utils/assetTypes.ts)', menu, ['STOCK', 'ETF', 'OTHER']);

        expectNoGaps(
            ASSET_TYPES.filter((type) => !menu.includes(type)),
            'ASSET_TYPE_MENU_ORDER in src/lib/utils/assetTypes.ts does not list these asset types. It is the only source of the asset type dropdown in the creation and edit dialog, so a type missing here cannot be chosen by any user, anywhere, and nothing reports it. This list used to be mapped straight from the enum and so was complete for free; it is hand-written now only to carry section titles, and this assertion is the price of that.',
        );
        // Bidirectional on purpose, unlike the lookup tables above. An extra value in a
        // lookup table is dead weight; an extra value *here* is offered to the user and
        // then rejected by the backend, because the enum is what the API validates.
        expectNoGaps(
            menu.filter((type) => !ASSET_TYPES.includes(type)),
            'ASSET_TYPE_MENU_ORDER in src/lib/utils/assetTypes.ts offers these values, but the backend AssetType enum does not define them. The dialog would let the user pick one and the API would reject the save.',
        );
        expect(new Set(menu).size, 'ASSET_TYPE_MENU_ORDER lists the same asset type more than once: the dropdown would show a duplicate row.').toBe(menu.length);

        // The ETF section title is emitted before the first member of the family, so a
        // family split in two would put the title over only part of what it names.
        const familyPositions = menu.map((type, index) => ({type, index})).filter(({type}) => type === 'ETF' || type.startsWith('ETF_'));
        expect(familyPositions.length, 'ASSET_TYPE_MENU_ORDER no longer contains the ETF family at all.').toBeGreaterThan(1);
        const span = familyPositions[familyPositions.length - 1].index - familyPositions[0].index + 1;
        expect(
            span,
            `the ETF family is not contiguous in ASSET_TYPE_MENU_ORDER (it spans ${span} slots for ${familyPositions.length} members). buildAssetTypeOptions() emits the section title before the first ETF row, so anything wedged inside the family would appear under that title without belonging to it.`,
        ).toBe(familyPositions.length);
    });

    it.each(I18N_LANGUAGES)('has an %s title for the ETF section', (language) => {
        const file = path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`);
        const sections = JSON.parse(read(file))?.assets?.typeSections ?? {};
        expect(typeof sections.ETF === 'string' && sections.ETF.trim() !== '', `src/lib/i18n/${language}.json has no assets.typeSections.ETF. The dropdown prints the raw key as the section title, so the user reads "assets.typeSections.ETF" above the ETF rows.`).toBe(true);
    });

    /**
     * The engine's synthetic cash bucket, upper-cased.
     *
     * `portfolio_engine.py` injects the cash slice into `by_type` and `by_sector`
     * under the literal `"Liquidity"` — Title Case, and not a member of
     * `AssetType`. It then travels the same type-keyed path as the real enum
     * values, so it needs a label under `assets.types` that no enum value will
     * ever name. The three assertions below hold that arrangement together.
     */
    const CASH_BUCKET_KEY = 'LIQUIDITY';

    it('keeps the cash bucket out of the asset type enum', () => {
        expect(
            ASSET_TYPES.includes(CASH_BUCKET_KEY),
            `${CASH_BUCKET_KEY} has become an AssetType. Cash is an account balance the engine injects, not an instrument anyone buys, and a money-market fund already has its own value (ETF_MONETARY). An enum member with this name would be counted twice: once as a real holding and once as the synthetic slice.`,
        ).toBe(false);
    });

    it('keeps primaryAssetType upper-casing its input', () => {
        const source = read(ASSET_TYPES_TS);
        const start = source.indexOf('export function primaryAssetType');
        expect(start, 'src/lib/utils/assetTypes.ts no longer exports primaryAssetType: contract K2 has moved or gone.').toBeGreaterThan(-1);
        const body = source.slice(start, source.indexOf('\n}', start));

        expect(
            body.includes('.toUpperCase()'),
            'primaryAssetType no longer upper-cases its input. AllocationHistoryChart resolves its label by concatenating "assets.types." with rawName.toUpperCase(), so the engine\'s Title Case "Liquidity" lines up with the catalogue only while both sides normalise the same way. Returning unknown input verbatim looks tidier and silently makes the cash slice miss every table keyed on the upper-case form — the colour first, since the label would still resolve.',
        ).toBe(true);
    });

    it.each(I18N_LANGUAGES)('has an %s label for the cash bucket, which no enum value names', (language) => {
        const file = path.join(FRONTEND_DIR, 'src', 'lib', 'i18n', `${language}.json`);
        const labels = JSON.parse(read(file))?.assets?.types ?? {};
        assertScraped(`assets.types (src/lib/i18n/${language}.json)`, Object.keys(labels), ['STOCK', 'ETF', 'OTHER']);

        expect(
            typeof labels[CASH_BUCKET_KEY] === 'string' && labels[CASH_BUCKET_KEY].trim() !== '',
            `src/lib/i18n/${language}.json has no assets.types.${CASH_BUCKET_KEY}. That key is the one entry under assets.types with no matching AssetType, and nothing references it literally because AllocationHistoryChart composes it — \`assets.types.\${rawName.toUpperCase()}\` — so no search, no linter and no static pass will ever connect the two. It looks dead, and it looks dead for a convincing reason. Deleting it makes the cash slice of the allocation chart print the raw key instead of a translation, in every language at once.`,
        ).toBe(true);
    });
});

/**
 * Contract K2 — `primaryAssetType`, as its consumers rely on it.
 *
 * The cash-bucket block above already pins the *text* of the function: it reads the
 * source and checks that `.toUpperCase()` is still in the body. That is a weaker net
 * than it looks. Changing the last line from `?? raw` to `?? type` leaves the
 * `.toUpperCase()` call untouched on the line above and hands the caller its own
 * spelling straight back — the textual assertion stays green while the contract is
 * gone. These two call the function instead.
 *
 * The property matters outside this file. G indexes a chart palette on the result, E
 * and F read the same contract, and every one of those tables answers an unknown key
 * with a fallback rather than an error: a grey badge, `other.png`, the raw i18n path.
 * Nobody verifies the invariant they all depend on, which is why it is pinned here,
 * once, where the function lives — and not a second time in each consumer's suite.
 */
describe('contract K2 — primaryAssetType behaviour', () => {
    /**
     * `assetTypes.ts` imports `$lib/api/generated`, which is gitignored. Every other
     * test in this file scrapes rather than imports precisely so that it still works
     * on a checkout where `api sync` has never run; a static import here would drag
     * all of them into that dependency, because one unresolvable import fails the
     * whole module at collection. So the import is dynamic and local to the two tests
     * that must genuinely *call* the function — behaviour cannot be scraped.
     *
     * A missing `generated.ts` is reported, not skipped: in a summary line a skipped
     * assertion about K2 and a satisfied one are the same absence of red.
     */
    async function importPrimaryAssetType(): Promise<(type: string | null | undefined) => string> {
        expect(existsSync(GENERATED_TS), 'src/lib/api/generated.ts is absent, so assetTypes.ts cannot be imported and this contract cannot be exercised. Run `./dev.py api sync`.').toBe(true);
        const module = await import('../assetTypes');
        expect(typeof module.primaryAssetType, 'src/lib/utils/assetTypes.ts no longer exports primaryAssetType: contract K2 has moved or gone.').toBe('function');
        return module.primaryAssetType;
    }

    it('returns an upper-case value for every spelling a caller can hand it', async () => {
        const primaryAssetType = await importPrimaryAssetType();
        const inputs = [
            ...ASSET_TYPES,
            ...ASSET_TYPES.map((type) => type.toLowerCase()),
            '  etf_stock  ',
            'Etf_Monetary',
            // The engine's own spelling of the synthetic cash bucket, injected Title Case
            // by portfolio_engine.py into by_type and by_sector alike.
            'Liquidity',
            'SOMETHING_NOBODY_HAS_ADDED_YET',
        ];
        assertScraped('primaryAssetType inputs', inputs, ['STOCK', 'ETF', 'OTHER']);

        const offenders = inputs.filter((input) => primaryAssetType(input) !== primaryAssetType(input).toUpperCase());
        expect(
            offenders,
            'primaryAssetType returned a value that is not upper-case for these inputs. Every table keyed on its result — the chart palette, PNG_MAP, BADGE_CLASS_MAP, the assets.types catalogue — looks the key up verbatim and answers a miss with a fallback instead of an error, so a single mixed-case result is not a crash but a wrong colour, a wrong icon and a raw i18n path, in four languages, with nothing logged.',
        ).toEqual([]);
    });

    it('folds nullish and blank input to OTHER, never to the empty string', async () => {
        const primaryAssetType = await importPrimaryAssetType();
        for (const input of [null, undefined, '', '   ']) {
            expect(
                primaryAssetType(input),
                `primaryAssetType(${JSON.stringify(input)}) must be "OTHER". Returning "" would be worse than returning a wrong type: no catalogue, palette or icon map holds an empty key, so every one of them would fall back at once and the slice would be drawn grey, unlabelled and untraceable. The whitespace case is the reason the implementation trims before it tests.`,
            ).toBe('OTHER');
        }
    });
});
