// @vitest-environment jsdom
/**
 * SignalTreeSelect — the D-K1 characterization net.
 *
 * Decision D-K1 (workstream K, R15) moves this component's mechanics into the generic
 * `ui/select/TreeSelect.svelte` and leaves `charts/SignalTreeSelect.svelte` behind as a thin adapter:
 * same path, same props, same exported types. This file pins what the signals panel does today. It is
 * written against the baseline (f1047f766) and must be green there *before* the move, so that the move
 * can be proven behaviour-neutral.
 *
 * DO NOT EDIT THIS FILE TO ACCOMMODATE THE REFACTOR. If it goes red after the move, the move changed
 * signals behaviour: fix the adapter (or TreeSelect), or bring the change to the developer as a
 * decision. Rewording a test until it passes again turns the net into a mirror.
 *
 * Who leans on the contract pinned here:
 * - `e2e/gallery.spec.ts` (`selectIndicatorFromTree`): the first group expands by itself on open, the
 *   group rows publish `aria-expanded`, a collapsed group is expanded with a click;
 * - `e2e/assets/asset-detail.spec.ts`: `signal-tree-group-*` / `signal-tree-option-*` looked up inside
 *   the signals panel (so the rows must live inside the component), Escape pressed on the trigger;
 * - `e2e/fx/fx-detail.spec.ts` and `ChartSignalsSection.test.ts`: `${testId}-button`, option test ids.
 *
 * Only the public contract is read: props in; test ids, ARIA and DOM out; `onchange` and the two-way
 * `value` out. Never a CSS class, never a translated string: the placeholder is a prop this file owns,
 * and element ids are random per instance, so an id is only ever compared with the id of the row found
 * by its test id. `value` is bound through an accessor pair on the props object, which is exactly what
 * a parent's `bind:value` compiles to.
 *
 * Timing: `open()` defers "first entry active, then focus the search box" with `setTimeout(0)`. Focus
 * is the observable end of that step, so every test waits for focus before touching the keyboard. The
 * reset after each keystroke in the search box has no observable end at all, so the one test that
 * types and then navigates drains it with fake timers instead of racing it.
 */
import {beforeAll, describe, expect, it, vi} from 'vitest';
import type {ComponentProps} from 'svelte';
import {fireEvent, render, screen, setupI18n, waitFor, within} from '$test/component';
import SignalTreeSelect, {type SignalTreeGroup, type SignalTreeItem} from './SignalTreeSelect.svelte';

const TEST_ID = 'signal-picker';
const PLACEHOLDER = 'Add an indicator';

/**
 * Three families of two, built the way `ChartSignalsSection` builds them: `searchText` is the caller's
 * lower-cased `value name subtitle [data]`, and the component matches it as given.
 *
 * Load-bearing letters (change them and the search tests stop meaning anything):
 * - 'average' matches sma and ema (trend) and atr (volatility, collapsed at open), not bands, atr's sibling;
 * - 'strength' matches rsi only, while the trend group's *label* contains it too;
 * - 'b' matches bands only: it is the printable-key seed.
 */
const GROUPS: SignalTreeGroup[] = [
    {
        key: 'trend',
        label: 'Trend strength',
        subtitle: 'Direction of the price',
        items: [
            {value: 'sma', icon: '📈', name: 'Simple average', subtitle: 'Arithmetic mean', searchText: 'sma simple average arithmetic mean'},
            {value: 'ema', icon: '📉', name: 'Exponential average', subtitle: 'Weighted mean', dataSubtitle: 'Uses: close', searchText: 'ema exponential average weighted mean uses: close'},
        ],
    },
    {
        key: 'momentum',
        label: 'Momentum',
        subtitle: 'Speed of the move',
        items: [
            {value: 'rsi', icon: '⚡', name: 'Relative strength', subtitle: 'Oscillator', searchText: 'rsi relative strength oscillator'},
            {value: 'macd', icon: '🌀', name: 'Convergence divergence', subtitle: 'Oscillator', searchText: 'macd convergence divergence oscillator'},
        ],
    },
    {
        key: 'volatility',
        label: 'Volatility',
        subtitle: 'Width of the swings',
        items: [
            {value: 'bands', icon: '🎯', name: 'Bollinger bands', subtitle: 'Two deviations', searchText: 'bands bollinger bands two deviations'},
            {value: 'atr', icon: '📏', name: 'True range', subtitle: 'Average of the range', searchText: 'atr true range average of the range'},
        ],
    },
];

/** Shaped like the comparison picker of the signals panel: one unlabelled group, rendered `flat`. */
const COMPARISON_ITEMS: SignalTreeItem[] = [
    {value: 'asset-comparison', icon: '📊', name: 'Other asset', subtitle: 'Overlay a second price', searchText: 'asset-comparison other asset overlay a second price'},
    {value: 'fx-pair', icon: '💱', name: 'Currency pair', subtitle: 'Overlay an exchange rate', searchText: 'fx-pair currency pair overlay an exchange rate'},
];
const FLAT_GROUPS: SignalTreeGroup[] = [{key: 'comparison', label: '', subtitle: '', items: COMPARISON_ITEMS}];

type TreeProps = ComponentProps<typeof SignalTreeSelect>;

function mount({value = '', ...props}: Partial<Omit<TreeProps, 'onchange'>> = {}) {
    const onchange = vi.fn();
    // The parent's variable behind `bind:value`: the component writes it through the setter below.
    const bound = {value};
    render(SignalTreeSelect, {
        groups: GROUPS,
        placeholder: PLACEHOLDER,
        testId: TEST_ID,
        ...props,
        onchange,
        get value() {
            return bound.value;
        },
        set value(next: string) {
            bound.value = next;
        },
    });
    return {onchange, bound, trigger: screen.getByTestId(`${TEST_ID}-button`)};
}

/** The component's own root. Rows are looked up inside it, as asset-detail.spec looks them up inside the signals panel. */
function root(): HTMLElement {
    return screen.getByTestId(TEST_ID);
}

function group(key: string): HTMLElement {
    return within(root()).getByTestId(`signal-tree-group-${key}`);
}

function queryGroup(key: string): HTMLElement | null {
    return within(root()).queryByTestId(`signal-tree-group-${key}`);
}

function option(value: string): HTMLElement {
    return within(root()).getByTestId(`signal-tree-option-${value}`);
}

function queryOption(value: string): HTMLElement | null {
    return within(root()).queryByTestId(`signal-tree-option-${value}`);
}

/** The search box held by the open trigger. Found by tag rather than role, so a change of input type cannot hide it. */
function searchBox(trigger: HTMLElement): HTMLInputElement {
    const input = trigger.querySelector('input');
    if (!input) throw new Error('the trigger holds no search box: the dropdown is not open');
    return input;
}

/** Opens with a click, then waits for the deferred step to end: focus lands right after "first entry active". */
async function openByClick(trigger: HTMLElement): Promise<HTMLInputElement> {
    await fireEvent.click(trigger);
    const input = searchBox(trigger);
    await waitFor(() => expect(input).toHaveFocus());
    return input;
}

/**
 * The highlight, read the way assistive tech reads it: the combobox and its focused search box both
 * point `aria-activedescendant` at the row, and that row alone is `aria-selected`. In this action picker
 * `aria-selected` is the keyboard/pointer highlight: no row ever marks the value.
 */
function expectActive(trigger: HTMLElement, row: HTMLElement) {
    expect(row.id).not.toBe('');
    expect(trigger).toHaveAttribute('aria-activedescendant', row.id);
    expect(searchBox(trigger)).toHaveAttribute('aria-activedescendant', row.id);
    const highlighted = root().querySelectorAll('[aria-selected="true"]');
    expect(highlighted).toHaveLength(1);
    expect(highlighted[0]).toBe(row);
}

describe('SignalTreeSelect — D-K1 characterization net', () => {
    beforeAll(async () => {
        await setupI18n();
    });

    describe('trigger and rows', () => {
        it('publishes its test ids on a focusable, closed combobox that announces a tree, and renders no row', () => {
            const {trigger} = mount();

            expect(root()).toContainElement(trigger);
            expect(trigger).toHaveAttribute('role', 'combobox');
            // Focusable on its own: Playwright's press() focuses the trigger before dispatching a key.
            expect(trigger).toHaveAttribute('tabindex', '0');
            expect(trigger).toHaveAttribute('aria-haspopup', 'tree');
            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(trigger).not.toHaveAttribute('aria-activedescendant');
            expect(trigger.querySelector('input')).toBeNull();
            expect(within(root()).queryByRole('tree')).toBeNull();
            expect(within(root()).queryAllByTestId(/^signal-tree-/)).toHaveLength(0);
        });

        it('is an action picker: the closed trigger shows the placeholder, never the chosen item, and the value never steers the tree', async () => {
            const {trigger, onchange, bound} = mount({value: 'rsi'});

            expect(trigger).toHaveTextContent(PLACEHOLDER);
            expect(trigger).not.toHaveTextContent('Relative strength');
            expect(trigger).not.toHaveTextContent('⚡');

            // Opening ignores the value: the first group expands, not the one holding rsi, and the first row is active.
            await openByClick(trigger);
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('rsi')).toBeNull();
            expectActive(trigger, group('trend'));

            // Choosing does not turn it into a form field either: the trigger goes back to the placeholder.
            await fireEvent.click(option('sma'));
            expect(onchange).toHaveBeenCalledExactlyOnceWith('sma');
            expect(bound.value).toBe('sma');
            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(trigger).toHaveTextContent(PLACEHOLDER);
            expect(trigger).not.toHaveTextContent('Simple average');
        });

        it('opens on click onto a focused search box inside the trigger, with the first group expanded by itself', async () => {
            const {trigger} = mount();

            const input = await openByClick(trigger);

            expect(trigger).toHaveAttribute('aria-expanded', 'true');
            expect(trigger).toContainElement(input);
            const tree = within(root()).getByRole('tree');
            expect(tree.id).not.toBe('');
            expect(trigger).toHaveAttribute('aria-controls', tree.id);
            // gallery.spec relies on this: the first family is open without a click, the others wait for one.
            expect(group('trend')).toHaveAttribute('role', 'treeitem');
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            expect(option('sma')).toBeVisible();
            expect(option('sma')).toHaveAttribute('role', 'treeitem');
            expect(option('ema')).toBeVisible();
            for (const key of ['momentum', 'volatility']) {
                expect(group(key)).toHaveAttribute('role', 'treeitem');
                expect(group(key)).toHaveAttribute('aria-expanded', 'false');
            }
            // The items of a collapsed group are not rendered at all, not merely hidden.
            for (const value of ['rsi', 'macd', 'bands', 'atr']) {
                expect(queryOption(value)).toBeNull();
            }
        });

        it('renders each option with its icon, name, subtitle and data subtitle, and each group row with its label and subtitle', async () => {
            const {trigger} = mount();
            await openByClick(trigger);

            const ema = option('ema');
            for (const text of ['📉', 'Exponential average', 'Weighted mean', 'Uses: close']) {
                expect(ema).toHaveTextContent(text);
            }
            const trend = group('trend');
            expect(trend).toHaveTextContent('Trend strength');
            expect(trend).toHaveTextContent('Direction of the price');
        });
    });

    describe('mouse', () => {
        it('closes when the trigger is clicked again, but not when the search box inside it is', async () => {
            const {trigger, onchange} = mount();
            const input = await openByClick(trigger);

            await fireEvent.click(input);
            expect(trigger).toHaveAttribute('aria-expanded', 'true');
            expect(group('trend')).toBeVisible();

            await fireEvent.click(trigger);
            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(within(root()).queryByRole('tree')).toBeNull();
            expect(onchange).not.toHaveBeenCalled();
        });

        it('toggles a group on click, rendering its items only while expanded, without selecting or closing', async () => {
            const {trigger, onchange} = mount();
            await openByClick(trigger);
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');

            await fireEvent.click(group('momentum'));
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'true');
            expect(option('rsi')).toBeVisible();
            expect(option('macd')).toBeVisible();
            // Groups are independent: expanding one leaves the other one expanded.
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');

            await fireEvent.click(group('momentum'));
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('rsi')).toBeNull();
            expect(queryOption('macd')).toBeNull();

            await fireEvent.click(group('trend'));
            expect(group('trend')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('sma')).toBeNull();

            expect(trigger).toHaveAttribute('aria-expanded', 'true');
            expect(onchange).not.toHaveBeenCalled();
        });

        it('keeps the expansion across close and reopen, and expands the first group by itself only when none is expanded', async () => {
            const {trigger} = mount();
            let input = await openByClick(trigger);
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            await fireEvent.click(group('trend'));
            await fireEvent.click(group('momentum'));
            await fireEvent.keyDown(input, {key: 'Escape'});
            expect(trigger).toHaveAttribute('aria-expanded', 'false');

            // One group is still expanded, so nothing expands by itself: the user's tree comes back as it was.
            input = await openByClick(trigger);
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'true');
            expect(group('trend')).toHaveAttribute('aria-expanded', 'false');

            // With every group collapsed, the next open expands the first one again.
            await fireEvent.click(group('momentum'));
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
            await fireEvent.keyDown(input, {key: 'Escape'});
            await openByClick(trigger);
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
        });

        it('selects an item on click, the way the gallery helper drives it: onchange once, bound value updated, closed', async () => {
            const {trigger, onchange, bound} = mount();
            await openByClick(trigger);

            // selectIndicatorFromTree(): expand the family only when it is collapsed, then click the option.
            const family = group('momentum');
            expect(family).toHaveAttribute('aria-expanded', 'false');
            await fireEvent.click(family);
            expect(family).toHaveAttribute('aria-expanded', 'true');
            await fireEvent.click(option('macd'));

            expect(onchange).toHaveBeenCalledExactlyOnceWith('macd');
            expect(bound.value).toBe('macd');
            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(within(root()).queryByRole('tree')).toBeNull();
            expect(queryOption('macd')).toBeNull();
        });

        it('moves the highlight to the row under the pointer, the same highlight Enter acts on', async () => {
            const {trigger, onchange} = mount();
            const input = await openByClick(trigger);

            await fireEvent.mouseEnter(group('volatility'));
            expectActive(trigger, group('volatility'));

            await fireEvent.mouseEnter(option('ema'));
            expectActive(trigger, option('ema'));

            await fireEvent.keyDown(input, {key: 'Enter'});
            expect(onchange).toHaveBeenCalledExactlyOnceWith('ema');
        });

        it('closes on a mousedown outside its container, never on one inside it', async () => {
            const {trigger, onchange} = mount();
            const input = await openByClick(trigger);

            // A real click begins with mousedown: were a press on a row to close the dropdown, no click could ever land on an option.
            await fireEvent.mouseDown(group('momentum'));
            await fireEvent.mouseDown(option('sma'));
            await fireEvent.mouseDown(input);
            expect(trigger).toHaveAttribute('aria-expanded', 'true');

            await fireEvent.mouseDown(document.body);

            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(within(root()).queryByRole('tree')).toBeNull();
            expect(onchange).not.toHaveBeenCalled();
        });
    });

    describe('search', () => {
        it('filters on searchText with a trimmed, lower-cased query, drops emptied groups and shows every matching group expanded', async () => {
            const {trigger} = mount();
            const input = await openByClick(trigger);

            await fireEvent.input(input, {target: {value: '  AVERAGE '}});

            // trend and volatility hold matches; volatility was collapsed, and shows expanded anyway.
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            expect(option('sma')).toBeVisible();
            expect(option('ema')).toBeVisible();
            expect(group('volatility')).toHaveAttribute('aria-expanded', 'true');
            expect(option('atr')).toBeVisible();
            // The filter works per item: bands shares its group with a match without being one.
            expect(queryOption('bands')).toBeNull();
            // momentum has no match: its row goes, and its items with it.
            expect(queryGroup('momentum')).toBeNull();
            expect(queryOption('rsi')).toBeNull();
            expect(queryOption('macd')).toBeNull();

            // The search is a view over the tree, not an edit of it: emptying it gives back what the user had.
            await fireEvent.input(input, {target: {value: ''}});
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
            expect(group('volatility')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('atr')).toBeNull();
        });

        it('does not search group labels', async () => {
            const {trigger} = mount();
            const input = await openByClick(trigger);

            await fireEvent.input(input, {target: {value: 'strength'}});

            expect(group('momentum')).toHaveAttribute('aria-expanded', 'true');
            expect(option('rsi')).toBeVisible();
            expect(queryOption('macd')).toBeNull();
            // 'Trend strength' matches as a label, yet no trend item matches: the group is dropped.
            expect(queryGroup('trend')).toBeNull();
            expect(queryOption('sma')).toBeNull();
        });

        it('with no match renders no row but an empty state, and Enter selects nothing', async () => {
            const {trigger, onchange} = mount();
            const input = await openByClick(trigger);

            await fireEvent.input(input, {target: {value: 'zzz-no-match'}});

            // The popup stays open, so the user is told why the list is empty...
            const tree = within(root()).getByRole('tree');
            expect(within(tree).queryAllByRole('treeitem')).toHaveLength(0);
            expect(within(root()).queryAllByTestId(/^signal-tree-/)).toHaveLength(0);
            // ...by a message whose wording belongs to the locale: its presence is the contract, not its text.
            expect(tree.textContent?.trim().length).toBeGreaterThan(0);
            // Nothing to point at, so nothing is announced as active.
            expect(input).not.toHaveAttribute('aria-activedescendant');

            await fireEvent.keyDown(input, {key: 'Enter'});
            expect(onchange).not.toHaveBeenCalled();
            expect(trigger).toHaveAttribute('aria-expanded', 'true');
        });

        it('offers a clear button while there is a query, which empties it and gives the focus back to the search box', async () => {
            const {trigger} = mount();
            const input = await openByClick(trigger);
            expect(within(trigger).queryByRole('button')).toBeNull();

            await fireEvent.input(input, {target: {value: 'average'}});
            const clear = within(trigger).getByRole('button');
            // A real click moves the focus onto the button first; the component must take it back.
            clear.focus();
            await fireEvent.click(clear);

            expect(input).toHaveValue('');
            expect(input).toHaveFocus();
            expect(trigger).toHaveAttribute('aria-expanded', 'true');
            expect(within(trigger).queryByRole('button')).toBeNull();
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
            expect(option('sma')).toBeVisible();
        });

        it('while searching, steps through the matching items only, from the first match, and Enter picks one', async () => {
            // Every keystroke in the search box re-arms "first match active" behind a zero-delay timer, and
            // nothing observable says when it lands: fake timers drain it deterministically instead of racing it.
            vi.useFakeTimers();
            try {
                const {trigger, onchange, bound} = mount();
                await fireEvent.click(trigger);
                await vi.runAllTimersAsync();
                const input = searchBox(trigger);
                expect(input).toHaveFocus();

                await fireEvent.input(input, {target: {value: 'average'}});
                await vi.runAllTimersAsync();
                expectActive(trigger, option('sma'));

                await fireEvent.keyDown(input, {key: 'ArrowDown'});
                expectActive(trigger, option('ema'));

                // Then atr: the volatility row rendered between them is not a stop while searching.
                await fireEvent.keyDown(input, {key: 'ArrowDown'});
                expectActive(trigger, option('atr'));

                await fireEvent.keyDown(input, {key: 'Enter'});
                expect(onchange).toHaveBeenCalledExactlyOnceWith('atr');
                expect(bound.value).toBe('atr');
                expect(trigger).toHaveAttribute('aria-expanded', 'false');
            } finally {
                vi.useRealTimers();
            }
        });
    });

    describe('keyboard', () => {
        // Entries of a fresh open, in order: trend (expanded by itself), sma, ema, momentum, volatility.
        it.each([
            {label: 'Enter', key: 'Enter', where: 'first', active: 'trend'},
            {label: 'Space', key: ' ', where: 'first', active: 'trend'},
            {label: 'ArrowDown', key: 'ArrowDown', where: 'first', active: 'trend'},
            {label: 'ArrowUp', key: 'ArrowUp', where: 'last', active: 'volatility'},
        ])('$label on the closed trigger opens it onto the $where entry', async ({key, active}) => {
            const {trigger} = mount();

            await fireEvent.keyDown(trigger, {key});

            expect(trigger).toHaveAttribute('aria-expanded', 'true');
            await waitFor(() => expect(searchBox(trigger)).toHaveFocus());
            expectActive(trigger, group(active));
        });

        it('opens on a printable key pressed on the closed trigger and seeds the search with it', async () => {
            const {trigger, onchange} = mount();

            await fireEvent.keyDown(trigger, {key: 'b'});

            expect(trigger).toHaveAttribute('aria-expanded', 'true');
            const input = searchBox(trigger);
            await waitFor(() => expect(input).toHaveValue('b'));
            await waitFor(() => expect(input).toHaveFocus());
            // The seed filters like typed text: only bands holds a 'b', in a group that was collapsed.
            expect(group('volatility')).toHaveAttribute('aria-expanded', 'true');
            expect(option('bands')).toBeVisible();
            expect(queryGroup('trend')).toBeNull();
            expectActive(trigger, option('bands'));

            await fireEvent.keyDown(input, {key: 'Enter'});
            expect(onchange).toHaveBeenCalledExactlyOnceWith('bands');
        });

        it('walks group rows and the items of expanded groups with ArrowDown and ArrowUp', async () => {
            const {trigger} = mount();
            const input = await openByClick(trigger);
            // Opening leaves the first entry active: the first group row.
            expectActive(trigger, group('trend'));

            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, option('sma'));

            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, option('ema'));

            // momentum is collapsed: after ema comes its row, not its items.
            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, group('momentum'));

            await fireEvent.keyDown(input, {key: 'ArrowUp'});
            expectActive(trigger, option('ema'));
        });

        it('jumps to the first and the last entry with Home and End', async () => {
            const {trigger} = mount();
            const input = await openByClick(trigger);
            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, option('sma'));

            await fireEvent.keyDown(input, {key: 'End'});
            expectActive(trigger, group('volatility'));

            await fireEvent.keyDown(input, {key: 'Home'});
            expectActive(trigger, group('trend'));
        });

        it('toggles the active group on Enter, and selects the active item on Enter', async () => {
            const {trigger, onchange, bound} = mount();
            const input = await openByClick(trigger);
            expectActive(trigger, group('trend'));

            await fireEvent.keyDown(input, {key: 'Enter'});
            expect(group('trend')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('sma')).toBeNull();
            // The row keeps the highlight, so a second Enter expands it again.
            expectActive(trigger, group('trend'));
            await fireEvent.keyDown(input, {key: 'Enter'});
            expect(group('trend')).toHaveAttribute('aria-expanded', 'true');
            expect(onchange).not.toHaveBeenCalled();

            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, option('ema'));
            await fireEvent.keyDown(input, {key: 'Enter'});

            expect(onchange).toHaveBeenCalledExactlyOnceWith('ema');
            expect(bound.value).toBe('ema');
            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(within(root()).queryByRole('tree')).toBeNull();
        });

        it('expands a collapsed group on ArrowRight and collapses an expanded one on ArrowLeft', async () => {
            const {trigger, onchange} = mount();
            const input = await openByClick(trigger);
            expectActive(trigger, group('trend'));

            await fireEvent.keyDown(input, {key: 'ArrowLeft'});
            expect(group('trend')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('sma')).toBeNull();

            // The entries are now the three group rows: one step down is momentum, collapsed.
            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, group('momentum'));
            await fireEvent.keyDown(input, {key: 'ArrowRight'});
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'true');
            expect(option('rsi')).toBeVisible();
            expectActive(trigger, group('momentum'));

            await fireEvent.keyDown(input, {key: 'ArrowLeft'});
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
            expect(queryOption('rsi')).toBeNull();
            expect(onchange).not.toHaveBeenCalled();
        });

        it('closes on Escape in the search box without selecting the highlighted item, and forgets the query', async () => {
            const {trigger, onchange, bound} = mount();
            let input = await openByClick(trigger);
            await fireEvent.input(input, {target: {value: 'average'}});
            // Whenever the post-keystroke reset lands, the first match is the highlight: Enter would pick sma.
            expectActive(trigger, option('sma'));

            await fireEvent.keyDown(input, {key: 'Escape'});

            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(trigger).not.toHaveAttribute('aria-activedescendant');
            expect(within(root()).queryByRole('tree')).toBeNull();
            expect(onchange).not.toHaveBeenCalled();
            expect(bound.value).toBe('');

            input = await openByClick(trigger);
            expect(input).toHaveValue('');
            expect(group('momentum')).toHaveAttribute('aria-expanded', 'false');
        });
    });

    describe('flat mode', () => {
        it('lists every item of every group as an option of a listbox, and renders no group row', async () => {
            const {trigger} = mount({flat: true});
            expect(trigger).toHaveAttribute('aria-haspopup', 'listbox');

            await openByClick(trigger);

            const listbox = within(root()).getByRole('listbox');
            expect(listbox.id).not.toBe('');
            expect(trigger).toHaveAttribute('aria-controls', listbox.id);
            expect(within(root()).queryByRole('tree')).toBeNull();
            expect(within(root()).queryAllByTestId(/^signal-tree-group-/)).toHaveLength(0);
            // Every group is flattened, in order, with nothing to expand first.
            const options = within(listbox).getAllByRole('option');
            expect(options.map((element) => element.getAttribute('data-testid'))).toEqual(['sma', 'ema', 'rsi', 'macd', 'bands', 'atr'].map((value) => `signal-tree-option-${value}`));
            expect(within(listbox).queryAllByRole('treeitem')).toHaveLength(0);
            expectActive(trigger, option('sma'));
        });

        it('moves between options with the arrows and selects with Enter, no group row in the way', async () => {
            const {trigger, onchange, bound} = mount({groups: FLAT_GROUPS, flat: true});
            const input = await openByClick(trigger);
            expectActive(trigger, option('asset-comparison'));

            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            expectActive(trigger, option('fx-pair'));
            await fireEvent.keyDown(input, {key: 'ArrowUp'});
            expectActive(trigger, option('asset-comparison'));
            await fireEvent.keyDown(input, {key: 'ArrowDown'});
            await fireEvent.keyDown(input, {key: 'Enter'});

            expect(onchange).toHaveBeenCalledExactlyOnceWith('fx-pair');
            expect(bound.value).toBe('fx-pair');
            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(within(root()).queryByRole('listbox')).toBeNull();
        });

        it('closes on Escape pressed on the trigger itself, where asset-detail.spec presses it', async () => {
            const {trigger, onchange} = mount({groups: FLAT_GROUPS, flat: true});
            await openByClick(trigger);
            expect(option('asset-comparison')).toBeVisible();

            // Playwright's press() focuses the trigger, then dispatches the key there rather than in the search box.
            trigger.focus();
            await fireEvent.keyDown(trigger, {key: 'Escape'});

            expect(trigger).toHaveAttribute('aria-expanded', 'false');
            expect(within(root()).queryByRole('listbox')).toBeNull();
            expect(onchange).not.toHaveBeenCalled();
        });
    });
});
